version: '3'
services:
  provider:
    build: .
    entrypoint: >
      airbloc server -c local/provider.yml --verbose
    depends_on:
      - mongo
    ports:
      - "2471:2471"
      - "2473:2473"

  controller:
    build: .
    entrypoint: >
      airbloc controller -c local/controller.yml --verbose
    depends_on:
      - mongo
    ports:
      - "2472:2472"
      - "2474:2474"

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
