// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/p2p/message.proto

package airbloc_p2p_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Topic int32

const (
	Topic_UNKNOWN                           Topic = 0
	Topic_AIRBLOC_REENCRYPTION_KEY_ANNOUNCE Topic = 1
	Topic_AIRBLOC_REENCRYPTION_KEY_REQUEST  Topic = 2
	Topic_AIRBLOC_REENCRYPTION_KEY_RESPONSE Topic = 3
	Topic_AIRBLOC_IDENTITY_ACCNOUNCE        Topic = 4
	Topic_AIRBLOC_IDENTITY_REQUEST          Topic = 5
	Topic_AIRBLOC_IDENTITY_RESPONSE         Topic = 6
	Topic_AIRBLOC_DATASYNC_ANNOUNCE         Topic = 7
	Topic_AIRBLOC_DATASYNC_REQUEST          Topic = 8
	Topic_AIRBLOC_DATASYNC_RESPONSE         Topic = 9
	Topic_AIRBLOC_DAC_ANNOUNCE              Topic = 10
	Topic_AIRBLOC_DAC_REQUEST               Topic = 11
	Topic_AIRBLOC_DAC_RESPONSE              Topic = 12
	Topic_TEST_PING                         Topic = 13
	Topic_TEST_PONG                         Topic = 14
)

var Topic_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "AIRBLOC_REENCRYPTION_KEY_ANNOUNCE",
	2:  "AIRBLOC_REENCRYPTION_KEY_REQUEST",
	3:  "AIRBLOC_REENCRYPTION_KEY_RESPONSE",
	4:  "AIRBLOC_IDENTITY_ACCNOUNCE",
	5:  "AIRBLOC_IDENTITY_REQUEST",
	6:  "AIRBLOC_IDENTITY_RESPONSE",
	7:  "AIRBLOC_DATASYNC_ANNOUNCE",
	8:  "AIRBLOC_DATASYNC_REQUEST",
	9:  "AIRBLOC_DATASYNC_RESPONSE",
	10: "AIRBLOC_DAC_ANNOUNCE",
	11: "AIRBLOC_DAC_REQUEST",
	12: "AIRBLOC_DAC_RESPONSE",
	13: "TEST_PING",
	14: "TEST_PONG",
}
var Topic_value = map[string]int32{
	"UNKNOWN":                           0,
	"AIRBLOC_REENCRYPTION_KEY_ANNOUNCE": 1,
	"AIRBLOC_REENCRYPTION_KEY_REQUEST":  2,
	"AIRBLOC_REENCRYPTION_KEY_RESPONSE": 3,
	"AIRBLOC_IDENTITY_ACCNOUNCE":        4,
	"AIRBLOC_IDENTITY_REQUEST":          5,
	"AIRBLOC_IDENTITY_RESPONSE":         6,
	"AIRBLOC_DATASYNC_ANNOUNCE":         7,
	"AIRBLOC_DATASYNC_REQUEST":          8,
	"AIRBLOC_DATASYNC_RESPONSE":         9,
	"AIRBLOC_DAC_ANNOUNCE":              10,
	"AIRBLOC_DAC_REQUEST":               11,
	"AIRBLOC_DAC_RESPONSE":              12,
	"TEST_PING":                         13,
	"TEST_PONG":                         14,
}

func (x Topic) String() string {
	return proto.EnumName(Topic_name, int32(x))
}
func (Topic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{0}
}

type ReEncryptionKeyAnnounce struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReEncryptionKeyAnnounce) Reset()         { *m = ReEncryptionKeyAnnounce{} }
func (m *ReEncryptionKeyAnnounce) String() string { return proto.CompactTextString(m) }
func (*ReEncryptionKeyAnnounce) ProtoMessage()    {}
func (*ReEncryptionKeyAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{0}
}
func (m *ReEncryptionKeyAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReEncryptionKeyAnnounce.Unmarshal(m, b)
}
func (m *ReEncryptionKeyAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReEncryptionKeyAnnounce.Marshal(b, m, deterministic)
}
func (dst *ReEncryptionKeyAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReEncryptionKeyAnnounce.Merge(dst, src)
}
func (m *ReEncryptionKeyAnnounce) XXX_Size() int {
	return xxx_messageInfo_ReEncryptionKeyAnnounce.Size(m)
}
func (m *ReEncryptionKeyAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ReEncryptionKeyAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ReEncryptionKeyAnnounce proto.InternalMessageInfo

type ReEncryptionKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReEncryptionKeyRequest) Reset()         { *m = ReEncryptionKeyRequest{} }
func (m *ReEncryptionKeyRequest) String() string { return proto.CompactTextString(m) }
func (*ReEncryptionKeyRequest) ProtoMessage()    {}
func (*ReEncryptionKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{1}
}
func (m *ReEncryptionKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReEncryptionKeyRequest.Unmarshal(m, b)
}
func (m *ReEncryptionKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReEncryptionKeyRequest.Marshal(b, m, deterministic)
}
func (dst *ReEncryptionKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReEncryptionKeyRequest.Merge(dst, src)
}
func (m *ReEncryptionKeyRequest) XXX_Size() int {
	return xxx_messageInfo_ReEncryptionKeyRequest.Size(m)
}
func (m *ReEncryptionKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReEncryptionKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReEncryptionKeyRequest proto.InternalMessageInfo

type ReEncryptionKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReEncryptionKeyResponse) Reset()         { *m = ReEncryptionKeyResponse{} }
func (m *ReEncryptionKeyResponse) String() string { return proto.CompactTextString(m) }
func (*ReEncryptionKeyResponse) ProtoMessage()    {}
func (*ReEncryptionKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{2}
}
func (m *ReEncryptionKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReEncryptionKeyResponse.Unmarshal(m, b)
}
func (m *ReEncryptionKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReEncryptionKeyResponse.Marshal(b, m, deterministic)
}
func (dst *ReEncryptionKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReEncryptionKeyResponse.Merge(dst, src)
}
func (m *ReEncryptionKeyResponse) XXX_Size() int {
	return xxx_messageInfo_ReEncryptionKeyResponse.Size(m)
}
func (m *ReEncryptionKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReEncryptionKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReEncryptionKeyResponse proto.InternalMessageInfo

type IdentityAnnounce struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityAnnounce) Reset()         { *m = IdentityAnnounce{} }
func (m *IdentityAnnounce) String() string { return proto.CompactTextString(m) }
func (*IdentityAnnounce) ProtoMessage()    {}
func (*IdentityAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{3}
}
func (m *IdentityAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityAnnounce.Unmarshal(m, b)
}
func (m *IdentityAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityAnnounce.Marshal(b, m, deterministic)
}
func (dst *IdentityAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityAnnounce.Merge(dst, src)
}
func (m *IdentityAnnounce) XXX_Size() int {
	return xxx_messageInfo_IdentityAnnounce.Size(m)
}
func (m *IdentityAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityAnnounce proto.InternalMessageInfo

type IdentityRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityRequest) Reset()         { *m = IdentityRequest{} }
func (m *IdentityRequest) String() string { return proto.CompactTextString(m) }
func (*IdentityRequest) ProtoMessage()    {}
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{4}
}
func (m *IdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityRequest.Unmarshal(m, b)
}
func (m *IdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityRequest.Marshal(b, m, deterministic)
}
func (dst *IdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityRequest.Merge(dst, src)
}
func (m *IdentityRequest) XXX_Size() int {
	return xxx_messageInfo_IdentityRequest.Size(m)
}
func (m *IdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityRequest proto.InternalMessageInfo

type IdentityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityResponse) Reset()         { *m = IdentityResponse{} }
func (m *IdentityResponse) String() string { return proto.CompactTextString(m) }
func (*IdentityResponse) ProtoMessage()    {}
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{5}
}
func (m *IdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityResponse.Unmarshal(m, b)
}
func (m *IdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityResponse.Marshal(b, m, deterministic)
}
func (dst *IdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityResponse.Merge(dst, src)
}
func (m *IdentityResponse) XXX_Size() int {
	return xxx_messageInfo_IdentityResponse.Size(m)
}
func (m *IdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityResponse proto.InternalMessageInfo

type DatasyncAnnounce struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatasyncAnnounce) Reset()         { *m = DatasyncAnnounce{} }
func (m *DatasyncAnnounce) String() string { return proto.CompactTextString(m) }
func (*DatasyncAnnounce) ProtoMessage()    {}
func (*DatasyncAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{6}
}
func (m *DatasyncAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasyncAnnounce.Unmarshal(m, b)
}
func (m *DatasyncAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasyncAnnounce.Marshal(b, m, deterministic)
}
func (dst *DatasyncAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasyncAnnounce.Merge(dst, src)
}
func (m *DatasyncAnnounce) XXX_Size() int {
	return xxx_messageInfo_DatasyncAnnounce.Size(m)
}
func (m *DatasyncAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasyncAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_DatasyncAnnounce proto.InternalMessageInfo

type DatasyncRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatasyncRequest) Reset()         { *m = DatasyncRequest{} }
func (m *DatasyncRequest) String() string { return proto.CompactTextString(m) }
func (*DatasyncRequest) ProtoMessage()    {}
func (*DatasyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{7}
}
func (m *DatasyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasyncRequest.Unmarshal(m, b)
}
func (m *DatasyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasyncRequest.Marshal(b, m, deterministic)
}
func (dst *DatasyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasyncRequest.Merge(dst, src)
}
func (m *DatasyncRequest) XXX_Size() int {
	return xxx_messageInfo_DatasyncRequest.Size(m)
}
func (m *DatasyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatasyncRequest proto.InternalMessageInfo

type DatasyncResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatasyncResponse) Reset()         { *m = DatasyncResponse{} }
func (m *DatasyncResponse) String() string { return proto.CompactTextString(m) }
func (*DatasyncResponse) ProtoMessage()    {}
func (*DatasyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{8}
}
func (m *DatasyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasyncResponse.Unmarshal(m, b)
}
func (m *DatasyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasyncResponse.Marshal(b, m, deterministic)
}
func (dst *DatasyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasyncResponse.Merge(dst, src)
}
func (m *DatasyncResponse) XXX_Size() int {
	return xxx_messageInfo_DatasyncResponse.Size(m)
}
func (m *DatasyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatasyncResponse proto.InternalMessageInfo

type DACAccounce struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DACAccounce) Reset()         { *m = DACAccounce{} }
func (m *DACAccounce) String() string { return proto.CompactTextString(m) }
func (*DACAccounce) ProtoMessage()    {}
func (*DACAccounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{9}
}
func (m *DACAccounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DACAccounce.Unmarshal(m, b)
}
func (m *DACAccounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DACAccounce.Marshal(b, m, deterministic)
}
func (dst *DACAccounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DACAccounce.Merge(dst, src)
}
func (m *DACAccounce) XXX_Size() int {
	return xxx_messageInfo_DACAccounce.Size(m)
}
func (m *DACAccounce) XXX_DiscardUnknown() {
	xxx_messageInfo_DACAccounce.DiscardUnknown(m)
}

var xxx_messageInfo_DACAccounce proto.InternalMessageInfo

type DACRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DACRequest) Reset()         { *m = DACRequest{} }
func (m *DACRequest) String() string { return proto.CompactTextString(m) }
func (*DACRequest) ProtoMessage()    {}
func (*DACRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{10}
}
func (m *DACRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DACRequest.Unmarshal(m, b)
}
func (m *DACRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DACRequest.Marshal(b, m, deterministic)
}
func (dst *DACRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DACRequest.Merge(dst, src)
}
func (m *DACRequest) XXX_Size() int {
	return xxx_messageInfo_DACRequest.Size(m)
}
func (m *DACRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DACRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DACRequest proto.InternalMessageInfo

type DACResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DACResponse) Reset()         { *m = DACResponse{} }
func (m *DACResponse) String() string { return proto.CompactTextString(m) }
func (*DACResponse) ProtoMessage()    {}
func (*DACResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{11}
}
func (m *DACResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DACResponse.Unmarshal(m, b)
}
func (m *DACResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DACResponse.Marshal(b, m, deterministic)
}
func (dst *DACResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DACResponse.Merge(dst, src)
}
func (m *DACResponse) XXX_Size() int {
	return xxx_messageInfo_DACResponse.Size(m)
}
func (m *DACResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DACResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DACResponse proto.InternalMessageInfo

type TestPing struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestPing) Reset()         { *m = TestPing{} }
func (m *TestPing) String() string { return proto.CompactTextString(m) }
func (*TestPing) ProtoMessage()    {}
func (*TestPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{12}
}
func (m *TestPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPing.Unmarshal(m, b)
}
func (m *TestPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPing.Marshal(b, m, deterministic)
}
func (dst *TestPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPing.Merge(dst, src)
}
func (m *TestPing) XXX_Size() int {
	return xxx_messageInfo_TestPing.Size(m)
}
func (m *TestPing) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPing.DiscardUnknown(m)
}

var xxx_messageInfo_TestPing proto.InternalMessageInfo

func (m *TestPing) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TestPong struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestPong) Reset()         { *m = TestPong{} }
func (m *TestPong) String() string { return proto.CompactTextString(m) }
func (*TestPong) ProtoMessage()    {}
func (*TestPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7d56e9ecde329e29, []int{13}
}
func (m *TestPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPong.Unmarshal(m, b)
}
func (m *TestPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPong.Marshal(b, m, deterministic)
}
func (dst *TestPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPong.Merge(dst, src)
}
func (m *TestPong) XXX_Size() int {
	return xxx_messageInfo_TestPong.Size(m)
}
func (m *TestPong) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPong.DiscardUnknown(m)
}

var xxx_messageInfo_TestPong proto.InternalMessageInfo

func (m *TestPong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReEncryptionKeyAnnounce)(nil), "airbloc.p2p.v1.ReEncryptionKeyAnnounce")
	proto.RegisterType((*ReEncryptionKeyRequest)(nil), "airbloc.p2p.v1.ReEncryptionKeyRequest")
	proto.RegisterType((*ReEncryptionKeyResponse)(nil), "airbloc.p2p.v1.ReEncryptionKeyResponse")
	proto.RegisterType((*IdentityAnnounce)(nil), "airbloc.p2p.v1.IdentityAnnounce")
	proto.RegisterType((*IdentityRequest)(nil), "airbloc.p2p.v1.IdentityRequest")
	proto.RegisterType((*IdentityResponse)(nil), "airbloc.p2p.v1.IdentityResponse")
	proto.RegisterType((*DatasyncAnnounce)(nil), "airbloc.p2p.v1.DatasyncAnnounce")
	proto.RegisterType((*DatasyncRequest)(nil), "airbloc.p2p.v1.DatasyncRequest")
	proto.RegisterType((*DatasyncResponse)(nil), "airbloc.p2p.v1.DatasyncResponse")
	proto.RegisterType((*DACAccounce)(nil), "airbloc.p2p.v1.DACAccounce")
	proto.RegisterType((*DACRequest)(nil), "airbloc.p2p.v1.DACRequest")
	proto.RegisterType((*DACResponse)(nil), "airbloc.p2p.v1.DACResponse")
	proto.RegisterType((*TestPing)(nil), "airbloc.p2p.v1.TestPing")
	proto.RegisterType((*TestPong)(nil), "airbloc.p2p.v1.TestPong")
	proto.RegisterEnum("airbloc.p2p.v1.Topic", Topic_name, Topic_value)
}

func init() { proto.RegisterFile("proto/p2p/message.proto", fileDescriptor_message_7d56e9ecde329e29) }

var fileDescriptor_message_7d56e9ecde329e29 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x61, 0x8b, 0xd3, 0x30,
	0x1c, 0xc6, 0x9d, 0xe7, 0xdd, 0x6e, 0xff, 0xdd, 0xce, 0x1a, 0xc5, 0xf5, 0x44, 0xe5, 0x1c, 0x27,
	0x88, 0x2f, 0x76, 0x78, 0x7e, 0x82, 0x98, 0x86, 0xa3, 0x4c, 0xd2, 0x9a, 0x66, 0x48, 0x5f, 0x95,
	0xae, 0x86, 0x51, 0xd0, 0x24, 0xae, 0x9d, 0xb0, 0xef, 0xe4, 0x87, 0x14, 0xb6, 0xa6, 0x0d, 0x73,
	0xb7, 0x97, 0x79, 0x9e, 0xe7, 0xf7, 0x0b, 0x2d, 0x04, 0xc6, 0x66, 0xa5, 0x6b, 0x7d, 0x6b, 0xee,
	0xcc, 0xed, 0x2f, 0x59, 0x55, 0xf9, 0x52, 0x4e, 0xb7, 0x09, 0xba, 0xcc, 0xcb, 0xd5, 0xe2, 0xa7,
	0x2e, 0xa6, 0xe6, 0xce, 0x4c, 0xff, 0x7c, 0x9a, 0x5c, 0xc1, 0x98, 0x4b, 0xaa, 0x8a, 0xd5, 0xc6,
	0xd4, 0xa5, 0x56, 0x33, 0xb9, 0xc1, 0x4a, 0xe9, 0xb5, 0x2a, 0xe4, 0xc4, 0x87, 0x97, 0x7b, 0x15,
	0x97, 0xbf, 0xd7, 0xb2, 0xaa, 0x0f, 0x40, 0x5c, 0x56, 0x46, 0xab, 0x4a, 0x4e, 0x10, 0x78, 0xe1,
	0x0f, 0xa9, 0xea, 0xb2, 0xee, 0x44, 0xcf, 0xe0, 0xa9, 0xcd, 0xac, 0xc1, 0x99, 0xb9, 0x68, 0x90,
	0xd7, 0x79, 0xb5, 0x51, 0x85, 0x8b, 0xda, 0xcc, 0x41, 0xbb, 0xa8, 0x41, 0x47, 0x30, 0x0c, 0x30,
	0xc1, 0x45, 0xb1, 0xa3, 0x2e, 0x00, 0x02, 0x4c, 0x2c, 0xb0, 0x2b, 0xdb, 0xed, 0x0d, 0x9c, 0x0b,
	0x59, 0xd5, 0x71, 0xa9, 0x96, 0xc8, 0x87, 0x7e, 0xf3, 0x7b, 0xfc, 0xde, 0x75, 0xef, 0xc3, 0x80,
	0xdb, 0x63, 0xbb, 0xd2, 0xc7, 0x56, 0x1f, 0xff, 0x9e, 0xc0, 0xa9, 0xd0, 0xa6, 0x2c, 0xd0, 0x10,
	0xfa, 0x73, 0x36, 0x63, 0xd1, 0x77, 0xe6, 0x3d, 0x42, 0xef, 0xe1, 0x1d, 0x0e, 0xf9, 0x97, 0xaf,
	0x11, 0xc9, 0x38, 0xa5, 0x8c, 0xf0, 0x34, 0x16, 0x61, 0xc4, 0xb2, 0x19, 0x4d, 0x33, 0xcc, 0x58,
	0x34, 0x67, 0x84, 0x7a, 0x3d, 0x74, 0x03, 0xd7, 0x0f, 0xce, 0x38, 0xfd, 0x36, 0xa7, 0x89, 0xf0,
	0x1e, 0x1f, 0x95, 0x71, 0x9a, 0xc4, 0x11, 0x4b, 0xa8, 0x77, 0x82, 0xde, 0xc2, 0x2b, 0x3b, 0x0b,
	0x03, 0xca, 0x44, 0x28, 0xd2, 0x0c, 0x13, 0xd2, 0x5c, 0xf6, 0x04, 0xbd, 0x06, 0xff, 0xbf, 0xde,
	0x5e, 0x72, 0x8a, 0xde, 0xc0, 0xd5, 0x81, 0xb6, 0x91, 0x9f, 0xb9, 0x75, 0x80, 0x05, 0x4e, 0x52,
	0x46, 0xba, 0x0f, 0xe9, 0xbb, 0xee, 0xb6, 0xb6, 0xee, 0xf3, 0x83, 0x70, 0xeb, 0x1e, 0x20, 0x1f,
	0x5e, 0x74, 0xb5, 0xa3, 0x05, 0x34, 0x86, 0xe7, 0x6e, 0x63, 0x8d, 0xc3, 0x7d, 0xa4, 0x95, 0x5d,
	0xa0, 0x11, 0x0c, 0x04, 0x4d, 0x44, 0x16, 0x87, 0xec, 0xde, 0x1b, 0x75, 0xc7, 0x88, 0xdd, 0x7b,
	0x97, 0x8b, 0xb3, 0xed, 0x1b, 0xf8, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x28, 0x08, 0x2d, 0xda,
	0x1e, 0x03, 0x00, 0x00,
}
