// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpc/v1/server/dauth.proto

package server

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	// Identity information (e.g. Email, Phone Number)
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// An address of the user delegate.
	Controller           string   `protobuf:"bytes,2,opt,name=controller,proto3" json:"controller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cc8b72c8d7fd76, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *SignInRequest) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

type SignInResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cc8b72c8d7fd76, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DAuthRequest struct {
	// ID of the user.
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// Name of the data type.
	DataType string `protobuf:"bytes,2,opt,name=dataType,proto3" json:"dataType,omitempty"`
	// Consent action type.
	Action uint32 `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	// Name of the app.
	AppName              string   `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DAuthRequest) Reset()         { *m = DAuthRequest{} }
func (m *DAuthRequest) String() string { return proto.CompactTextString(m) }
func (*DAuthRequest) ProtoMessage()    {}
func (*DAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cc8b72c8d7fd76, []int{2}
}

func (m *DAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DAuthRequest.Unmarshal(m, b)
}
func (m *DAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DAuthRequest.Marshal(b, m, deterministic)
}
func (m *DAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DAuthRequest.Merge(m, src)
}
func (m *DAuthRequest) XXX_Size() int {
	return xxx_messageInfo_DAuthRequest.Size(m)
}
func (m *DAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DAuthRequest proto.InternalMessageInfo

func (m *DAuthRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DAuthRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *DAuthRequest) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *DAuthRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type GetAuthorizationsRequest struct {
	// ID of the user.
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// Name of the app.
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorizationsRequest) Reset()         { *m = GetAuthorizationsRequest{} }
func (m *GetAuthorizationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorizationsRequest) ProtoMessage()    {}
func (*GetAuthorizationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cc8b72c8d7fd76, []int{3}
}

func (m *GetAuthorizationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorizationsRequest.Unmarshal(m, b)
}
func (m *GetAuthorizationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorizationsRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorizationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorizationsRequest.Merge(m, src)
}
func (m *GetAuthorizationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorizationsRequest.Size(m)
}
func (m *GetAuthorizationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorizationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorizationsRequest proto.InternalMessageInfo

func (m *GetAuthorizationsRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *GetAuthorizationsRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type GetAuthorizationsResponse struct {
	// true if the user has been done DAuth to given app at least one time.
	HasAuthorizedBefore bool `protobuf:"varint,1,opt,name=hasAuthorizedBefore,proto3" json:"hasAuthorizedBefore,omitempty"`
	// list of the authorization settings of the user to the app.
	Authorizations       []*GetAuthorizationsResponse_Authorization `protobuf:"bytes,2,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *GetAuthorizationsResponse) Reset()         { *m = GetAuthorizationsResponse{} }
func (m *GetAuthorizationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorizationsResponse) ProtoMessage()    {}
func (*GetAuthorizationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cc8b72c8d7fd76, []int{4}
}

func (m *GetAuthorizationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorizationsResponse.Unmarshal(m, b)
}
func (m *GetAuthorizationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorizationsResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorizationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorizationsResponse.Merge(m, src)
}
func (m *GetAuthorizationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorizationsResponse.Size(m)
}
func (m *GetAuthorizationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorizationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorizationsResponse proto.InternalMessageInfo

func (m *GetAuthorizationsResponse) GetHasAuthorizedBefore() bool {
	if m != nil {
		return m.HasAuthorizedBefore
	}
	return false
}

func (m *GetAuthorizationsResponse) GetAuthorizations() []*GetAuthorizationsResponse_Authorization {
	if m != nil {
		return m.Authorizations
	}
	return nil
}

type GetAuthorizationsResponse_Authorization struct {
	Action               uint32   `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	DataType             string   `protobuf:"bytes,2,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Authorized           bool     `protobuf:"varint,3,opt,name=authorized,proto3" json:"authorized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorizationsResponse_Authorization) Reset() {
	*m = GetAuthorizationsResponse_Authorization{}
}
func (m *GetAuthorizationsResponse_Authorization) String() string { return proto.CompactTextString(m) }
func (*GetAuthorizationsResponse_Authorization) ProtoMessage()    {}
func (*GetAuthorizationsResponse_Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cc8b72c8d7fd76, []int{4, 0}
}

func (m *GetAuthorizationsResponse_Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorizationsResponse_Authorization.Unmarshal(m, b)
}
func (m *GetAuthorizationsResponse_Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorizationsResponse_Authorization.Marshal(b, m, deterministic)
}
func (m *GetAuthorizationsResponse_Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorizationsResponse_Authorization.Merge(m, src)
}
func (m *GetAuthorizationsResponse_Authorization) XXX_Size() int {
	return xxx_messageInfo_GetAuthorizationsResponse_Authorization.Size(m)
}
func (m *GetAuthorizationsResponse_Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorizationsResponse_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorizationsResponse_Authorization proto.InternalMessageInfo

func (m *GetAuthorizationsResponse_Authorization) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *GetAuthorizationsResponse_Authorization) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *GetAuthorizationsResponse_Authorization) GetAuthorized() bool {
	if m != nil {
		return m.Authorized
	}
	return false
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "airbloc.rpc.v1.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "airbloc.rpc.v1.SignInResponse")
	proto.RegisterType((*DAuthRequest)(nil), "airbloc.rpc.v1.DAuthRequest")
	proto.RegisterType((*GetAuthorizationsRequest)(nil), "airbloc.rpc.v1.GetAuthorizationsRequest")
	proto.RegisterType((*GetAuthorizationsResponse)(nil), "airbloc.rpc.v1.GetAuthorizationsResponse")
	proto.RegisterType((*GetAuthorizationsResponse_Authorization)(nil), "airbloc.rpc.v1.GetAuthorizationsResponse.Authorization")
}

func init() { proto.RegisterFile("proto/rpc/v1/server/dauth.proto", fileDescriptor_66cc8b72c8d7fd76) }

var fileDescriptor_66cc8b72c8d7fd76 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x55, 0xdc, 0x36, 0xa4, 0x03, 0x89, 0xc4, 0x22, 0x55, 0xc6, 0x84, 0x10, 0xe5, 0x14, 0x0e,
	0xec, 0x92, 0xf6, 0xc0, 0x05, 0x0e, 0xad, 0x8a, 0xaa, 0x0a, 0x89, 0x83, 0xe1, 0xc4, 0x05, 0x6d,
	0xd6, 0x5b, 0xdb, 0x92, 0xb3, 0xb3, 0xac, 0xd7, 0x41, 0xe9, 0x6f, 0xf0, 0x31, 0xfc, 0x1e, 0xca,
	0xda, 0x0e, 0x76, 0x48, 0xa3, 0x88, 0x93, 0x35, 0xf3, 0x66, 0xde, 0xcc, 0x3c, 0xcf, 0x2c, 0xbc,
	0xd2, 0x06, 0x2d, 0x32, 0xa3, 0x05, 0x5b, 0xce, 0x58, 0x2e, 0xcd, 0x52, 0x1a, 0x16, 0xf1, 0xc2,
	0x26, 0xd4, 0x21, 0x64, 0xc0, 0x53, 0x33, 0xcf, 0x50, 0x50, 0xa3, 0x05, 0x5d, 0xce, 0x82, 0x61,
	0x8c, 0x18, 0x67, 0x92, 0x71, 0x9d, 0x32, 0xae, 0x14, 0x5a, 0x6e, 0x53, 0x54, 0x79, 0x19, 0x1d,
	0xbc, 0xa8, 0x50, 0x67, 0xcd, 0x8b, 0x3b, 0x26, 0x17, 0xda, 0xae, 0x4a, 0x70, 0xf2, 0x09, 0xfa,
	0x5f, 0xd2, 0x58, 0xdd, 0xaa, 0x50, 0xfe, 0x28, 0x64, 0x6e, 0x49, 0x00, 0xbd, 0x34, 0x92, 0xca,
	0xa6, 0x76, 0xe5, 0x77, 0xc6, 0x9d, 0xe9, 0x69, 0xb8, 0xb1, 0xc9, 0x08, 0x40, 0xa0, 0xb2, 0x06,
	0xb3, 0x4c, 0x1a, 0xdf, 0x73, 0x68, 0xc3, 0x33, 0xa1, 0x30, 0xa8, 0xc9, 0x72, 0x8d, 0x2a, 0x97,
	0x64, 0x08, 0xa7, 0x5c, 0x08, 0x2c, 0x94, 0xbd, 0x8d, 0x2a, 0xba, 0xbf, 0x8e, 0xc9, 0x3d, 0x3c,
	0xb9, 0xbe, 0x2c, 0x6c, 0x52, 0xd7, 0xde, 0x1b, 0xbd, 0xee, 0x2c, 0xe2, 0x96, 0x7f, 0x5d, 0x69,
	0x59, 0xd5, 0xde, 0xd8, 0xe4, 0x0c, 0xba, 0x5c, 0xac, 0x87, 0xf6, 0x8f, 0xc6, 0x9d, 0x69, 0x3f,
	0xac, 0x2c, 0xe2, 0xc3, 0x23, 0xae, 0xf5, 0x67, 0xbe, 0x90, 0xfe, 0xb1, 0x4b, 0xa9, 0xcd, 0x49,
	0x08, 0xfe, 0x8d, 0xb4, 0xeb, 0xea, 0x68, 0xd2, 0xfb, 0x52, 0xb0, 0xc3, 0xfa, 0x68, 0x70, 0x7a,
	0x6d, 0xce, 0x5f, 0x1e, 0x3c, 0xdf, 0x41, 0x5a, 0x69, 0xf1, 0x16, 0x9e, 0x25, 0x3c, 0xaf, 0x41,
	0x19, 0x5d, 0xc9, 0x3b, 0x34, 0xd2, 0xf1, 0xf7, 0xc2, 0x5d, 0x10, 0xf9, 0x0e, 0x03, 0xde, 0xe2,
	0xf2, 0xbd, 0xf1, 0xd1, 0xf4, 0xf1, 0xf9, 0x3b, 0xda, 0x5e, 0x00, 0xfa, 0x60, 0x51, 0xda, 0x72,
	0x87, 0x5b, 0x74, 0x81, 0x80, 0x7e, 0x2b, 0xa0, 0xa1, 0x63, 0xa7, 0xa5, 0xe3, 0x3e, 0xed, 0x47,
	0x00, 0x7c, 0xd3, 0xb9, 0xd3, 0xbf, 0x17, 0x36, 0x3c, 0xe7, 0xbf, 0x3d, 0x38, 0x71, 0xbf, 0x99,
	0xdc, 0x40, 0xb7, 0xdc, 0x0f, 0xf2, 0x72, 0x7b, 0x82, 0xd6, 0x12, 0x06, 0xa3, 0x87, 0xe0, 0x4a,
	0xca, 0x04, 0x9e, 0xfe, 0x33, 0x32, 0x99, 0x1e, 0xa0, 0x4a, 0x49, 0xff, 0xfa, 0x60, 0xfd, 0xc8,
	0x07, 0x38, 0xb9, 0xcc, 0x32, 0xfc, 0x49, 0x86, 0xdb, 0x39, 0xcd, 0xcd, 0x0d, 0xce, 0x68, 0x79,
	0x64, 0xb4, 0x3e, 0x32, 0xfa, 0x71, 0x7d, 0x64, 0xe4, 0x3d, 0x1c, 0x5f, 0x4b, 0xb5, 0xfa, 0xbf,
	0xec, 0xab, 0x8b, 0x6f, 0xb3, 0x38, 0xb5, 0x49, 0x31, 0xa7, 0x02, 0x17, 0xac, 0x62, 0xa8, 0xbf,
	0x6f, 0x62, 0x64, 0x3b, 0x1e, 0x8a, 0x79, 0xd7, 0x39, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xce, 0xfb, 0xe1, 0xb7, 0x46, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DAuthClient is the client API for DAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DAuthClient interface {
	//*
	// SignIn takes an email of user and returns an user account ID if the account is exists.
	// Otherwise, it creates new account using the email, and returns an ID of the newly created account.
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	//*
	// GetAuthorization returns a list of the data authorization settings
	// which are done to collections of this app by given user.
	GetAuthorizations(ctx context.Context, in *GetAuthorizationsRequest, opts ...grpc.CallOption) (*GetAuthorizationsResponse, error)
	//*
	// Allow turns on user's data collection authorization settings for the given collection.
	//
	// Note that this is one-time only; Once you set an authorization to the collection,
	// then you cannot change it through this API. Only users can modify the settings.
	Allow(ctx context.Context, in *DAuthRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	//*
	// Deny turns off user's data collection authorization settings for the given collection.
	//
	// Note that this is one-time only; Once you set an authorization to the collection,
	// then you cannot change it through this API. Only users can modify the settings.
	Deny(ctx context.Context, in *DAuthRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type dAuthClient struct {
	cc *grpc.ClientConn
}

func NewDAuthClient(cc *grpc.ClientConn) DAuthClient {
	return &dAuthClient{cc}
}

func (c *dAuthClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/airbloc.rpc.v1.DAuth/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAuthClient) GetAuthorizations(ctx context.Context, in *GetAuthorizationsRequest, opts ...grpc.CallOption) (*GetAuthorizationsResponse, error) {
	out := new(GetAuthorizationsResponse)
	err := c.cc.Invoke(ctx, "/airbloc.rpc.v1.DAuth/GetAuthorizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAuthClient) Allow(ctx context.Context, in *DAuthRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/airbloc.rpc.v1.DAuth/Allow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAuthClient) Deny(ctx context.Context, in *DAuthRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/airbloc.rpc.v1.DAuth/Deny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAuthServer is the server API for DAuth service.
type DAuthServer interface {
	//*
	// SignIn takes an email of user and returns an user account ID if the account is exists.
	// Otherwise, it creates new account using the email, and returns an ID of the newly created account.
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	//*
	// GetAuthorization returns a list of the data authorization settings
	// which are done to collections of this app by given user.
	GetAuthorizations(context.Context, *GetAuthorizationsRequest) (*GetAuthorizationsResponse, error)
	//*
	// Allow turns on user's data collection authorization settings for the given collection.
	//
	// Note that this is one-time only; Once you set an authorization to the collection,
	// then you cannot change it through this API. Only users can modify the settings.
	Allow(context.Context, *DAuthRequest) (*empty.Empty, error)
	//*
	// Deny turns off user's data collection authorization settings for the given collection.
	//
	// Note that this is one-time only; Once you set an authorization to the collection,
	// then you cannot change it through this API. Only users can modify the settings.
	Deny(context.Context, *DAuthRequest) (*empty.Empty, error)
}

func RegisterDAuthServer(s *grpc.Server, srv DAuthServer) {
	s.RegisterService(&_DAuth_serviceDesc, srv)
}

func _DAuth_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAuthServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbloc.rpc.v1.DAuth/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAuthServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAuth_GetAuthorizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAuthServer).GetAuthorizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbloc.rpc.v1.DAuth/GetAuthorizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAuthServer).GetAuthorizations(ctx, req.(*GetAuthorizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAuth_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAuthServer).Allow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbloc.rpc.v1.DAuth/Allow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAuthServer).Allow(ctx, req.(*DAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAuth_Deny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAuthServer).Deny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbloc.rpc.v1.DAuth/Deny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAuthServer).Deny(ctx, req.(*DAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "airbloc.rpc.v1.DAuth",
	HandlerType: (*DAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _DAuth_SignIn_Handler,
		},
		{
			MethodName: "GetAuthorizations",
			Handler:    _DAuth_GetAuthorizations_Handler,
		},
		{
			MethodName: "Allow",
			Handler:    _DAuth_Allow_Handler,
		},
		{
			MethodName: "Deny",
			Handler:    _DAuth_Deny_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc/v1/server/dauth.proto",
}
