// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpc/v1/server/user.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{0}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetDataReponse struct {
	Collections          []*GetDataReponse_Collection `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetDataReponse) Reset()         { *m = GetDataReponse{} }
func (m *GetDataReponse) String() string { return proto.CompactTextString(m) }
func (*GetDataReponse) ProtoMessage()    {}
func (*GetDataReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{1}
}

func (m *GetDataReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReponse.Unmarshal(m, b)
}
func (m *GetDataReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReponse.Marshal(b, m, deterministic)
}
func (m *GetDataReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReponse.Merge(m, src)
}
func (m *GetDataReponse) XXX_Size() int {
	return xxx_messageInfo_GetDataReponse.Size(m)
}
func (m *GetDataReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReponse proto.InternalMessageInfo

func (m *GetDataReponse) GetCollections() []*GetDataReponse_Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

type GetDataReponse_Data struct {
	CollectedAt          int64    `protobuf:"varint,1,opt,name=collectedAt,proto3" json:"collectedAt,omitempty"`
	IngestedAt           int64    `protobuf:"varint,2,opt,name=ingestedAt,proto3" json:"ingestedAt,omitempty"`
	Payload              string   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataReponse_Data) Reset()         { *m = GetDataReponse_Data{} }
func (m *GetDataReponse_Data) String() string { return proto.CompactTextString(m) }
func (*GetDataReponse_Data) ProtoMessage()    {}
func (*GetDataReponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{1, 0}
}

func (m *GetDataReponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReponse_Data.Unmarshal(m, b)
}
func (m *GetDataReponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReponse_Data.Marshal(b, m, deterministic)
}
func (m *GetDataReponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReponse_Data.Merge(m, src)
}
func (m *GetDataReponse_Data) XXX_Size() int {
	return xxx_messageInfo_GetDataReponse_Data.Size(m)
}
func (m *GetDataReponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReponse_Data proto.InternalMessageInfo

func (m *GetDataReponse_Data) GetCollectedAt() int64 {
	if m != nil {
		return m.CollectedAt
	}
	return 0
}

func (m *GetDataReponse_Data) GetIngestedAt() int64 {
	if m != nil {
		return m.IngestedAt
	}
	return 0
}

func (m *GetDataReponse_Data) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type GetDataReponse_Collection struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []*GetDataReponse_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDataReponse_Collection) Reset()         { *m = GetDataReponse_Collection{} }
func (m *GetDataReponse_Collection) String() string { return proto.CompactTextString(m) }
func (*GetDataReponse_Collection) ProtoMessage()    {}
func (*GetDataReponse_Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{1, 1}
}

func (m *GetDataReponse_Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReponse_Collection.Unmarshal(m, b)
}
func (m *GetDataReponse_Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReponse_Collection.Marshal(b, m, deterministic)
}
func (m *GetDataReponse_Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReponse_Collection.Merge(m, src)
}
func (m *GetDataReponse_Collection) XXX_Size() int {
	return xxx_messageInfo_GetDataReponse_Collection.Size(m)
}
func (m *GetDataReponse_Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReponse_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReponse_Collection proto.InternalMessageInfo

func (m *GetDataReponse_Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDataReponse_Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetDataReponse_Collection) GetData() []*GetDataReponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetDataIdsResponse struct {
	Collections          []*GetDataIdsResponse_Collection `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetDataIdsResponse) Reset()         { *m = GetDataIdsResponse{} }
func (m *GetDataIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataIdsResponse) ProtoMessage()    {}
func (*GetDataIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{2}
}

func (m *GetDataIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataIdsResponse.Unmarshal(m, b)
}
func (m *GetDataIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataIdsResponse.Marshal(b, m, deterministic)
}
func (m *GetDataIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataIdsResponse.Merge(m, src)
}
func (m *GetDataIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataIdsResponse.Size(m)
}
func (m *GetDataIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataIdsResponse proto.InternalMessageInfo

func (m *GetDataIdsResponse) GetCollections() []*GetDataIdsResponse_Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

type GetDataIdsResponse_DataInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IngestedAt           int64    `protobuf:"varint,2,opt,name=ingestedAt,proto3" json:"ingestedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataIdsResponse_DataInfo) Reset()         { *m = GetDataIdsResponse_DataInfo{} }
func (m *GetDataIdsResponse_DataInfo) String() string { return proto.CompactTextString(m) }
func (*GetDataIdsResponse_DataInfo) ProtoMessage()    {}
func (*GetDataIdsResponse_DataInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{2, 0}
}

func (m *GetDataIdsResponse_DataInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataIdsResponse_DataInfo.Unmarshal(m, b)
}
func (m *GetDataIdsResponse_DataInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataIdsResponse_DataInfo.Marshal(b, m, deterministic)
}
func (m *GetDataIdsResponse_DataInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataIdsResponse_DataInfo.Merge(m, src)
}
func (m *GetDataIdsResponse_DataInfo) XXX_Size() int {
	return xxx_messageInfo_GetDataIdsResponse_DataInfo.Size(m)
}
func (m *GetDataIdsResponse_DataInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataIdsResponse_DataInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataIdsResponse_DataInfo proto.InternalMessageInfo

func (m *GetDataIdsResponse_DataInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDataIdsResponse_DataInfo) GetIngestedAt() int64 {
	if m != nil {
		return m.IngestedAt
	}
	return 0
}

type GetDataIdsResponse_Collection struct {
	CollectionId         string                         `protobuf:"bytes,3,opt,name=collectionId,proto3" json:"collectionId,omitempty"`
	DataInfoes           []*GetDataIdsResponse_DataInfo `protobuf:"bytes,4,rep,name=dataInfoes,proto3" json:"dataInfoes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetDataIdsResponse_Collection) Reset()         { *m = GetDataIdsResponse_Collection{} }
func (m *GetDataIdsResponse_Collection) String() string { return proto.CompactTextString(m) }
func (*GetDataIdsResponse_Collection) ProtoMessage()    {}
func (*GetDataIdsResponse_Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_93739d9e0922a9b9, []int{2, 1}
}

func (m *GetDataIdsResponse_Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataIdsResponse_Collection.Unmarshal(m, b)
}
func (m *GetDataIdsResponse_Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataIdsResponse_Collection.Marshal(b, m, deterministic)
}
func (m *GetDataIdsResponse_Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataIdsResponse_Collection.Merge(m, src)
}
func (m *GetDataIdsResponse_Collection) XXX_Size() int {
	return xxx_messageInfo_GetDataIdsResponse_Collection.Size(m)
}
func (m *GetDataIdsResponse_Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataIdsResponse_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataIdsResponse_Collection proto.InternalMessageInfo

func (m *GetDataIdsResponse_Collection) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

func (m *GetDataIdsResponse_Collection) GetDataInfoes() []*GetDataIdsResponse_DataInfo {
	if m != nil {
		return m.DataInfoes
	}
	return nil
}

func init() {
	proto.RegisterType((*UserId)(nil), "airbloc.rpc.v1.UserId")
	proto.RegisterType((*GetDataReponse)(nil), "airbloc.rpc.v1.GetDataReponse")
	proto.RegisterType((*GetDataReponse_Data)(nil), "airbloc.rpc.v1.GetDataReponse.Data")
	proto.RegisterType((*GetDataReponse_Collection)(nil), "airbloc.rpc.v1.GetDataReponse.Collection")
	proto.RegisterType((*GetDataIdsResponse)(nil), "airbloc.rpc.v1.GetDataIdsResponse")
	proto.RegisterType((*GetDataIdsResponse_DataInfo)(nil), "airbloc.rpc.v1.GetDataIdsResponse.DataInfo")
	proto.RegisterType((*GetDataIdsResponse_Collection)(nil), "airbloc.rpc.v1.GetDataIdsResponse.Collection")
}

func init() { proto.RegisterFile("proto/rpc/v1/server/user.proto", fileDescriptor_93739d9e0922a9b9) }

var fileDescriptor_93739d9e0922a9b9 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0x25, 0x1f, 0xe8, 0xf3, 0xfa, 0x70, 0x31, 0x0b, 0x09, 0x79, 0x20, 0x21, 0x6f, 0xe3, 0xe3,
	0x61, 0x06, 0x75, 0xf1, 0xe0, 0xed, 0x6c, 0x0b, 0xad, 0xb8, 0x28, 0x04, 0xba, 0xe9, 0x6e, 0x92,
	0x8c, 0x69, 0x20, 0x66, 0xc2, 0xcc, 0x44, 0x70, 0xd1, 0x5f, 0xd1, 0x3f, 0xd0, 0x1f, 0xd0, 0x1f,
	0x59, 0x9c, 0x24, 0x9a, 0xb4, 0x5a, 0xbb, 0xca, 0xcc, 0xbd, 0xe7, 0x9c, 0x7b, 0xcf, 0x61, 0x02,
	0xa3, 0x9c, 0x33, 0xc9, 0x30, 0xcf, 0x43, 0xbc, 0x9d, 0x62, 0x41, 0xf9, 0x96, 0x72, 0x5c, 0x08,
	0xca, 0x3d, 0xd5, 0x40, 0x03, 0x92, 0xf0, 0x20, 0x65, 0xa1, 0xc7, 0xf3, 0xd0, 0xdb, 0x4e, 0xed,
	0x5f, 0x31, 0x63, 0x71, 0x4a, 0xb1, 0xea, 0x06, 0xc5, 0x1a, 0xd3, 0x4d, 0x2e, 0x77, 0x25, 0xd8,
	0x75, 0xa0, 0xf3, 0x20, 0x28, 0x5f, 0x46, 0x68, 0x08, 0x9d, 0x42, 0x9d, 0x2c, 0xcd, 0xd1, 0xc6,
	0x3d, 0xbf, 0xba, 0xb9, 0x6f, 0x3a, 0x0c, 0x6e, 0xa9, 0xbc, 0x21, 0x92, 0xf8, 0x34, 0x67, 0x99,
	0xa0, 0x68, 0x05, 0xfd, 0x90, 0xa5, 0x29, 0x0d, 0x65, 0xc2, 0x32, 0x61, 0x69, 0x8e, 0x31, 0xee,
	0xcf, 0xfe, 0x78, 0xed, 0xb9, 0x5e, 0x9b, 0xe4, 0x5d, 0x1f, 0x18, 0x7e, 0x93, 0x6d, 0x07, 0x60,
	0xee, 0x61, 0xc8, 0x39, 0x88, 0xd2, 0x68, 0x21, 0xd5, 0x12, 0x86, 0xdf, 0x2c, 0xa1, 0x11, 0x40,
	0x92, 0xc5, 0x54, 0x94, 0x00, 0x5d, 0x01, 0x1a, 0x15, 0x64, 0x41, 0x37, 0x27, 0xbb, 0x94, 0x91,
	0xc8, 0x32, 0x94, 0x85, 0xfa, 0x6a, 0x27, 0x00, 0xc7, 0xf1, 0x68, 0x00, 0x7a, 0x52, 0xbb, 0xd4,
	0x93, 0x08, 0x21, 0x30, 0x33, 0xb2, 0xa1, 0x4a, 0xb1, 0xe7, 0xab, 0x33, 0xfa, 0x07, 0x66, 0x44,
	0x24, 0xb1, 0x0c, 0xe5, 0xed, 0xf7, 0x05, 0x6f, 0xea, 0xac, 0x08, 0xee, 0xab, 0x0e, 0xa8, 0xea,
	0x2e, 0x23, 0xe1, 0x53, 0x51, 0x46, 0x76, 0x7f, 0x2a, 0xb2, 0xc9, 0x19, 0xd9, 0x06, 0xf1, 0x6c,
	0x6c, 0xff, 0xe1, 0x87, 0x82, 0x66, 0x6b, 0xf6, 0xc9, 0xd0, 0x85, 0xa0, 0xec, 0xe7, 0x56, 0x1c,
	0x2e, 0xfc, 0x3c, 0x0a, 0x2f, 0xeb, 0xec, 0x5a, 0x35, 0xb4, 0x02, 0x88, 0xaa, 0x69, 0x54, 0x58,
	0xa6, 0xda, 0xfe, 0xef, 0x37, 0xb6, 0xaf, 0x57, 0xf4, 0x1b, 0xf4, 0xd9, 0x8b, 0x06, 0xe6, 0xfe,
	0xd1, 0xa1, 0x05, 0x74, 0x2b, 0x0e, 0x1a, 0x7e, 0x14, 0x2b, 0x5f, 0xa5, 0x3d, 0xfa, 0x3a, 0x79,
	0x74, 0x07, 0x70, 0x1c, 0x7b, 0x56, 0xc5, 0xbd, 0xbc, 0xea, 0xd5, 0xfc, 0x71, 0x1a, 0x27, 0xf2,
	0xa9, 0x08, 0xbc, 0x90, 0x6d, 0x70, 0x85, 0xaf, 0xbf, 0x93, 0x98, 0xe1, 0x13, 0xbf, 0x5d, 0xd0,
	0x51, 0xc5, 0xf9, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xe2, 0x2c, 0xec, 0x94, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetData(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*GetDataReponse, error)
	GetDataIds(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*GetDataIdsResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetData(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*GetDataReponse, error) {
	out := new(GetDataReponse)
	err := c.cc.Invoke(ctx, "/airbloc.rpc.v1.User/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetDataIds(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*GetDataIdsResponse, error) {
	out := new(GetDataIdsResponse)
	err := c.cc.Invoke(ctx, "/airbloc.rpc.v1.User/GetDataIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetData(context.Context, *UserId) (*GetDataReponse, error)
	GetDataIds(context.Context, *UserId) (*GetDataIdsResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbloc.rpc.v1.User/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetData(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetDataIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetDataIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbloc.rpc.v1.User/GetDataIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetDataIds(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "airbloc.rpc.v1.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _User_GetData_Handler,
		},
		{
			MethodName: "GetDataIds",
			Handler:    _User_GetDataIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc/v1/server/user.proto",
}
