// Code generated by MockGen. DO NOT EDIT.
// Source: accounts_wrapper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	adapter "github.com/airbloc/airbloc-go/shared/adapter"
	types "github.com/airbloc/airbloc-go/shared/types"
	gomock "github.com/golang/mock/gomock"
	bind "github.com/klaytn/klaytn/accounts/abi/bind"
	types0 "github.com/klaytn/klaytn/blockchain/types"
	common "github.com/klaytn/klaytn/common"
	event "github.com/klaytn/klaytn/event"
)

// MockIAccountsManager is a mock of IAccountsManager interface
type MockIAccountsManager struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsManagerMockRecorder
}

// MockIAccountsManagerMockRecorder is the mock recorder for MockIAccountsManager
type MockIAccountsManagerMockRecorder struct {
	mock *MockIAccountsManager
}

// NewMockIAccountsManager creates a new mock instance
func NewMockIAccountsManager(ctrl *gomock.Controller) *MockIAccountsManager {
	mock := &MockIAccountsManager{ctrl: ctrl}
	mock.recorder = &MockIAccountsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsManager) EXPECT() *MockIAccountsManagerMockRecorder {
	return m.recorder
}

// Address mocks base method
func (m *MockIAccountsManager) Address() common.Address {
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(common.Address)
	return ret0
}

// Address indicates an expected call of Address
func (mr *MockIAccountsManagerMockRecorder) Address() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockIAccountsManager)(nil).Address))
}

// TxHash mocks base method
func (m *MockIAccountsManager) TxHash() common.Hash {
	ret := m.ctrl.Call(m, "TxHash")
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// TxHash indicates an expected call of TxHash
func (mr *MockIAccountsManagerMockRecorder) TxHash() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxHash", reflect.TypeOf((*MockIAccountsManager)(nil).TxHash))
}

// CreatedAt mocks base method
func (m *MockIAccountsManager) CreatedAt() *big.Int {
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt
func (mr *MockIAccountsManagerMockRecorder) CreatedAt() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockIAccountsManager)(nil).CreatedAt))
}

// Accounts mocks base method
func (m *MockIAccountsManager) Accounts(arg0 types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "Accounts", arg0)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accounts indicates an expected call of Accounts
func (mr *MockIAccountsManagerMockRecorder) Accounts(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockIAccountsManager)(nil).Accounts), arg0)
}

// Exists mocks base method
func (m *MockIAccountsManager) Exists(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "Exists", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists
func (mr *MockIAccountsManagerMockRecorder) Exists(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIAccountsManager)(nil).Exists), accountId)
}

// GetAccount mocks base method
func (m *MockIAccountsManager) GetAccount(accountId types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "GetAccount", accountId)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount
func (mr *MockIAccountsManagerMockRecorder) GetAccount(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIAccountsManager)(nil).GetAccount), accountId)
}

// GetAccountId mocks base method
func (m *MockIAccountsManager) GetAccountId(sender common.Address) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountId", sender)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId
func (mr *MockIAccountsManagerMockRecorder) GetAccountId(sender interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockIAccountsManager)(nil).GetAccountId), sender)
}

// GetAccountIdFromSignature mocks base method
func (m *MockIAccountsManager) GetAccountIdFromSignature(messageHash common.Hash, signature []byte) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountIdFromSignature", messageHash, signature)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdFromSignature indicates an expected call of GetAccountIdFromSignature
func (mr *MockIAccountsManagerMockRecorder) GetAccountIdFromSignature(messageHash, signature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdFromSignature", reflect.TypeOf((*MockIAccountsManager)(nil).GetAccountIdFromSignature), messageHash, signature)
}

// IdentityHashToAccount mocks base method
func (m *MockIAccountsManager) IdentityHashToAccount(arg0 common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "IdentityHashToAccount", arg0)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityHashToAccount indicates an expected call of IdentityHashToAccount
func (mr *MockIAccountsManagerMockRecorder) IdentityHashToAccount(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityHashToAccount", reflect.TypeOf((*MockIAccountsManager)(nil).IdentityHashToAccount), arg0)
}

// IsControllerOf mocks base method
func (m *MockIAccountsManager) IsControllerOf(sender common.Address, accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsControllerOf", sender, accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsControllerOf indicates an expected call of IsControllerOf
func (mr *MockIAccountsManagerMockRecorder) IsControllerOf(sender, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsControllerOf", reflect.TypeOf((*MockIAccountsManager)(nil).IsControllerOf), sender, accountId)
}

// IsTemporary mocks base method
func (m *MockIAccountsManager) IsTemporary(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsTemporary", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemporary indicates an expected call of IsTemporary
func (mr *MockIAccountsManagerMockRecorder) IsTemporary(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemporary", reflect.TypeOf((*MockIAccountsManager)(nil).IsTemporary), accountId)
}

// NumberOfAccounts mocks base method
func (m *MockIAccountsManager) NumberOfAccounts() (*big.Int, error) {
	ret := m.ctrl.Call(m, "NumberOfAccounts")
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberOfAccounts indicates an expected call of NumberOfAccounts
func (mr *MockIAccountsManagerMockRecorder) NumberOfAccounts() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfAccounts", reflect.TypeOf((*MockIAccountsManager)(nil).NumberOfAccounts))
}

// Create mocks base method
func (m *MockIAccountsManager) Create(ctx context.Context) (types.ID, error) {
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIAccountsManagerMockRecorder) Create(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountsManager)(nil).Create), ctx)
}

// CreateTemporary mocks base method
func (m *MockIAccountsManager) CreateTemporary(ctx context.Context, identityHash common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "CreateTemporary", ctx, identityHash)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemporary indicates an expected call of CreateTemporary
func (mr *MockIAccountsManagerMockRecorder) CreateTemporary(ctx, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemporary", reflect.TypeOf((*MockIAccountsManager)(nil).CreateTemporary), ctx, identityHash)
}

// SetController mocks base method
func (m *MockIAccountsManager) SetController(ctx context.Context, controller common.Address) error {
	ret := m.ctrl.Call(m, "SetController", ctx, controller)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetController indicates an expected call of SetController
func (mr *MockIAccountsManagerMockRecorder) SetController(ctx, controller interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetController", reflect.TypeOf((*MockIAccountsManager)(nil).SetController), ctx, controller)
}

// UnlockTemporary mocks base method
func (m *MockIAccountsManager) UnlockTemporary(ctx context.Context, identityPreimage common.Hash, newOwner common.Address, passwordSignature []byte) error {
	ret := m.ctrl.Call(m, "UnlockTemporary", ctx, identityPreimage, newOwner, passwordSignature)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockTemporary indicates an expected call of UnlockTemporary
func (mr *MockIAccountsManagerMockRecorder) UnlockTemporary(ctx, identityPreimage, newOwner, passwordSignature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTemporary", reflect.TypeOf((*MockIAccountsManager)(nil).UnlockTemporary), ctx, identityPreimage, newOwner, passwordSignature)
}

// FilterSignUp mocks base method
func (m *MockIAccountsManager) FilterSignUp(opts *bind.FilterOpts, owner []common.Address) (*adapter.AccountsSignUpIterator, error) {
	ret := m.ctrl.Call(m, "FilterSignUp", opts, owner)
	ret0, _ := ret[0].(*adapter.AccountsSignUpIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSignUp indicates an expected call of FilterSignUp
func (mr *MockIAccountsManagerMockRecorder) FilterSignUp(opts, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSignUp", reflect.TypeOf((*MockIAccountsManager)(nil).FilterSignUp), opts, owner)
}

// FilterTemporaryCreated mocks base method
func (m *MockIAccountsManager) FilterTemporaryCreated(opts *bind.FilterOpts, proxy []common.Address, identityHash []common.Hash) (*adapter.AccountsTemporaryCreatedIterator, error) {
	ret := m.ctrl.Call(m, "FilterTemporaryCreated", opts, proxy, identityHash)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreatedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTemporaryCreated indicates an expected call of FilterTemporaryCreated
func (mr *MockIAccountsManagerMockRecorder) FilterTemporaryCreated(opts, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTemporaryCreated", reflect.TypeOf((*MockIAccountsManager)(nil).FilterTemporaryCreated), opts, proxy, identityHash)
}

// FilterUnlocked mocks base method
func (m *MockIAccountsManager) FilterUnlocked(opts *bind.FilterOpts, identityHash []common.Hash, accountId []types.ID) (*adapter.AccountsUnlockedIterator, error) {
	ret := m.ctrl.Call(m, "FilterUnlocked", opts, identityHash, accountId)
	ret0, _ := ret[0].(*adapter.AccountsUnlockedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterUnlocked indicates an expected call of FilterUnlocked
func (mr *MockIAccountsManagerMockRecorder) FilterUnlocked(opts, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUnlocked", reflect.TypeOf((*MockIAccountsManager)(nil).FilterUnlocked), opts, identityHash, accountId)
}

// WatchSignUp mocks base method
func (m *MockIAccountsManager) WatchSignUp(opts *bind.WatchOpts, sink chan<- *adapter.AccountsSignUp, owner []common.Address) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchSignUp", opts, sink, owner)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchSignUp indicates an expected call of WatchSignUp
func (mr *MockIAccountsManagerMockRecorder) WatchSignUp(opts, sink, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchSignUp", reflect.TypeOf((*MockIAccountsManager)(nil).WatchSignUp), opts, sink, owner)
}

// WatchTemporaryCreated mocks base method
func (m *MockIAccountsManager) WatchTemporaryCreated(opts *bind.WatchOpts, sink chan<- *adapter.AccountsTemporaryCreated, proxy []common.Address, identityHash []common.Hash) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchTemporaryCreated", opts, sink, proxy, identityHash)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchTemporaryCreated indicates an expected call of WatchTemporaryCreated
func (mr *MockIAccountsManagerMockRecorder) WatchTemporaryCreated(opts, sink, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchTemporaryCreated", reflect.TypeOf((*MockIAccountsManager)(nil).WatchTemporaryCreated), opts, sink, proxy, identityHash)
}

// WatchUnlocked mocks base method
func (m *MockIAccountsManager) WatchUnlocked(opts *bind.WatchOpts, sink chan<- *adapter.AccountsUnlocked, identityHash []common.Hash, accountId []types.ID) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchUnlocked", opts, sink, identityHash, accountId)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchUnlocked indicates an expected call of WatchUnlocked
func (mr *MockIAccountsManagerMockRecorder) WatchUnlocked(opts, sink, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchUnlocked", reflect.TypeOf((*MockIAccountsManager)(nil).WatchUnlocked), opts, sink, identityHash, accountId)
}

// MockIAccountsCalls is a mock of IAccountsCalls interface
type MockIAccountsCalls struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsCallsMockRecorder
}

// MockIAccountsCallsMockRecorder is the mock recorder for MockIAccountsCalls
type MockIAccountsCallsMockRecorder struct {
	mock *MockIAccountsCalls
}

// NewMockIAccountsCalls creates a new mock instance
func NewMockIAccountsCalls(ctrl *gomock.Controller) *MockIAccountsCalls {
	mock := &MockIAccountsCalls{ctrl: ctrl}
	mock.recorder = &MockIAccountsCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsCalls) EXPECT() *MockIAccountsCallsMockRecorder {
	return m.recorder
}

// Accounts mocks base method
func (m *MockIAccountsCalls) Accounts(arg0 types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "Accounts", arg0)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accounts indicates an expected call of Accounts
func (mr *MockIAccountsCallsMockRecorder) Accounts(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockIAccountsCalls)(nil).Accounts), arg0)
}

// Exists mocks base method
func (m *MockIAccountsCalls) Exists(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "Exists", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists
func (mr *MockIAccountsCallsMockRecorder) Exists(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIAccountsCalls)(nil).Exists), accountId)
}

// GetAccount mocks base method
func (m *MockIAccountsCalls) GetAccount(accountId types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "GetAccount", accountId)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount
func (mr *MockIAccountsCallsMockRecorder) GetAccount(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIAccountsCalls)(nil).GetAccount), accountId)
}

// GetAccountId mocks base method
func (m *MockIAccountsCalls) GetAccountId(sender common.Address) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountId", sender)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId
func (mr *MockIAccountsCallsMockRecorder) GetAccountId(sender interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockIAccountsCalls)(nil).GetAccountId), sender)
}

// GetAccountIdFromSignature mocks base method
func (m *MockIAccountsCalls) GetAccountIdFromSignature(messageHash common.Hash, signature []byte) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountIdFromSignature", messageHash, signature)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdFromSignature indicates an expected call of GetAccountIdFromSignature
func (mr *MockIAccountsCallsMockRecorder) GetAccountIdFromSignature(messageHash, signature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdFromSignature", reflect.TypeOf((*MockIAccountsCalls)(nil).GetAccountIdFromSignature), messageHash, signature)
}

// IdentityHashToAccount mocks base method
func (m *MockIAccountsCalls) IdentityHashToAccount(arg0 common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "IdentityHashToAccount", arg0)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityHashToAccount indicates an expected call of IdentityHashToAccount
func (mr *MockIAccountsCallsMockRecorder) IdentityHashToAccount(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityHashToAccount", reflect.TypeOf((*MockIAccountsCalls)(nil).IdentityHashToAccount), arg0)
}

// IsControllerOf mocks base method
func (m *MockIAccountsCalls) IsControllerOf(sender common.Address, accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsControllerOf", sender, accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsControllerOf indicates an expected call of IsControllerOf
func (mr *MockIAccountsCallsMockRecorder) IsControllerOf(sender, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsControllerOf", reflect.TypeOf((*MockIAccountsCalls)(nil).IsControllerOf), sender, accountId)
}

// IsTemporary mocks base method
func (m *MockIAccountsCalls) IsTemporary(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsTemporary", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemporary indicates an expected call of IsTemporary
func (mr *MockIAccountsCallsMockRecorder) IsTemporary(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemporary", reflect.TypeOf((*MockIAccountsCalls)(nil).IsTemporary), accountId)
}

// NumberOfAccounts mocks base method
func (m *MockIAccountsCalls) NumberOfAccounts() (*big.Int, error) {
	ret := m.ctrl.Call(m, "NumberOfAccounts")
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberOfAccounts indicates an expected call of NumberOfAccounts
func (mr *MockIAccountsCallsMockRecorder) NumberOfAccounts() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfAccounts", reflect.TypeOf((*MockIAccountsCalls)(nil).NumberOfAccounts))
}

// MockIAccountsTransacts is a mock of IAccountsTransacts interface
type MockIAccountsTransacts struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsTransactsMockRecorder
}

// MockIAccountsTransactsMockRecorder is the mock recorder for MockIAccountsTransacts
type MockIAccountsTransactsMockRecorder struct {
	mock *MockIAccountsTransacts
}

// NewMockIAccountsTransacts creates a new mock instance
func NewMockIAccountsTransacts(ctrl *gomock.Controller) *MockIAccountsTransacts {
	mock := &MockIAccountsTransacts{ctrl: ctrl}
	mock.recorder = &MockIAccountsTransactsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsTransacts) EXPECT() *MockIAccountsTransactsMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockIAccountsTransacts) Create(ctx context.Context) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIAccountsTransactsMockRecorder) Create(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountsTransacts)(nil).Create), ctx)
}

// CreateTemporary mocks base method
func (m *MockIAccountsTransacts) CreateTemporary(ctx context.Context, identityHash common.Hash) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "CreateTemporary", ctx, identityHash)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemporary indicates an expected call of CreateTemporary
func (mr *MockIAccountsTransactsMockRecorder) CreateTemporary(ctx, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemporary", reflect.TypeOf((*MockIAccountsTransacts)(nil).CreateTemporary), ctx, identityHash)
}

// SetController mocks base method
func (m *MockIAccountsTransacts) SetController(ctx context.Context, controller common.Address) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "SetController", ctx, controller)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetController indicates an expected call of SetController
func (mr *MockIAccountsTransactsMockRecorder) SetController(ctx, controller interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetController", reflect.TypeOf((*MockIAccountsTransacts)(nil).SetController), ctx, controller)
}

// UnlockTemporary mocks base method
func (m *MockIAccountsTransacts) UnlockTemporary(ctx context.Context, identityPreimage common.Hash, newOwner common.Address, passwordSignature []byte) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "UnlockTemporary", ctx, identityPreimage, newOwner, passwordSignature)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockTemporary indicates an expected call of UnlockTemporary
func (mr *MockIAccountsTransactsMockRecorder) UnlockTemporary(ctx, identityPreimage, newOwner, passwordSignature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTemporary", reflect.TypeOf((*MockIAccountsTransacts)(nil).UnlockTemporary), ctx, identityPreimage, newOwner, passwordSignature)
}

// MockIAccountsEvents is a mock of IAccountsEvents interface
type MockIAccountsEvents struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsEventsMockRecorder
}

// MockIAccountsEventsMockRecorder is the mock recorder for MockIAccountsEvents
type MockIAccountsEventsMockRecorder struct {
	mock *MockIAccountsEvents
}

// NewMockIAccountsEvents creates a new mock instance
func NewMockIAccountsEvents(ctrl *gomock.Controller) *MockIAccountsEvents {
	mock := &MockIAccountsEvents{ctrl: ctrl}
	mock.recorder = &MockIAccountsEventsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsEvents) EXPECT() *MockIAccountsEventsMockRecorder {
	return m.recorder
}

// FilterSignUp mocks base method
func (m *MockIAccountsEvents) FilterSignUp(opts *bind.FilterOpts, owner []common.Address) (*adapter.AccountsSignUpIterator, error) {
	ret := m.ctrl.Call(m, "FilterSignUp", opts, owner)
	ret0, _ := ret[0].(*adapter.AccountsSignUpIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSignUp indicates an expected call of FilterSignUp
func (mr *MockIAccountsEventsMockRecorder) FilterSignUp(opts, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSignUp", reflect.TypeOf((*MockIAccountsEvents)(nil).FilterSignUp), opts, owner)
}

// FilterTemporaryCreated mocks base method
func (m *MockIAccountsEvents) FilterTemporaryCreated(opts *bind.FilterOpts, proxy []common.Address, identityHash []common.Hash) (*adapter.AccountsTemporaryCreatedIterator, error) {
	ret := m.ctrl.Call(m, "FilterTemporaryCreated", opts, proxy, identityHash)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreatedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTemporaryCreated indicates an expected call of FilterTemporaryCreated
func (mr *MockIAccountsEventsMockRecorder) FilterTemporaryCreated(opts, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTemporaryCreated", reflect.TypeOf((*MockIAccountsEvents)(nil).FilterTemporaryCreated), opts, proxy, identityHash)
}

// FilterUnlocked mocks base method
func (m *MockIAccountsEvents) FilterUnlocked(opts *bind.FilterOpts, identityHash []common.Hash, accountId []types.ID) (*adapter.AccountsUnlockedIterator, error) {
	ret := m.ctrl.Call(m, "FilterUnlocked", opts, identityHash, accountId)
	ret0, _ := ret[0].(*adapter.AccountsUnlockedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterUnlocked indicates an expected call of FilterUnlocked
func (mr *MockIAccountsEventsMockRecorder) FilterUnlocked(opts, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUnlocked", reflect.TypeOf((*MockIAccountsEvents)(nil).FilterUnlocked), opts, identityHash, accountId)
}

// ParseSignUpFromReceipt mocks base method
func (m *MockIAccountsEvents) ParseSignUpFromReceipt(receipt *types0.Receipt) (*adapter.AccountsSignUp, error) {
	ret := m.ctrl.Call(m, "ParseSignUpFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsSignUp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSignUpFromReceipt indicates an expected call of ParseSignUpFromReceipt
func (mr *MockIAccountsEventsMockRecorder) ParseSignUpFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSignUpFromReceipt", reflect.TypeOf((*MockIAccountsEvents)(nil).ParseSignUpFromReceipt), receipt)
}

// ParseTemporaryCreatedFromReceipt mocks base method
func (m *MockIAccountsEvents) ParseTemporaryCreatedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsTemporaryCreated, error) {
	ret := m.ctrl.Call(m, "ParseTemporaryCreatedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTemporaryCreatedFromReceipt indicates an expected call of ParseTemporaryCreatedFromReceipt
func (mr *MockIAccountsEventsMockRecorder) ParseTemporaryCreatedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTemporaryCreatedFromReceipt", reflect.TypeOf((*MockIAccountsEvents)(nil).ParseTemporaryCreatedFromReceipt), receipt)
}

// ParseUnlockedFromReceipt mocks base method
func (m *MockIAccountsEvents) ParseUnlockedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsUnlocked, error) {
	ret := m.ctrl.Call(m, "ParseUnlockedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsUnlocked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseUnlockedFromReceipt indicates an expected call of ParseUnlockedFromReceipt
func (mr *MockIAccountsEventsMockRecorder) ParseUnlockedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUnlockedFromReceipt", reflect.TypeOf((*MockIAccountsEvents)(nil).ParseUnlockedFromReceipt), receipt)
}

// WatchSignUp mocks base method
func (m *MockIAccountsEvents) WatchSignUp(opts *bind.WatchOpts, sink chan<- *adapter.AccountsSignUp, owner []common.Address) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchSignUp", opts, sink, owner)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchSignUp indicates an expected call of WatchSignUp
func (mr *MockIAccountsEventsMockRecorder) WatchSignUp(opts, sink, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchSignUp", reflect.TypeOf((*MockIAccountsEvents)(nil).WatchSignUp), opts, sink, owner)
}

// WatchTemporaryCreated mocks base method
func (m *MockIAccountsEvents) WatchTemporaryCreated(opts *bind.WatchOpts, sink chan<- *adapter.AccountsTemporaryCreated, proxy []common.Address, identityHash []common.Hash) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchTemporaryCreated", opts, sink, proxy, identityHash)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchTemporaryCreated indicates an expected call of WatchTemporaryCreated
func (mr *MockIAccountsEventsMockRecorder) WatchTemporaryCreated(opts, sink, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchTemporaryCreated", reflect.TypeOf((*MockIAccountsEvents)(nil).WatchTemporaryCreated), opts, sink, proxy, identityHash)
}

// WatchUnlocked mocks base method
func (m *MockIAccountsEvents) WatchUnlocked(opts *bind.WatchOpts, sink chan<- *adapter.AccountsUnlocked, identityHash []common.Hash, accountId []types.ID) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchUnlocked", opts, sink, identityHash, accountId)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchUnlocked indicates an expected call of WatchUnlocked
func (mr *MockIAccountsEventsMockRecorder) WatchUnlocked(opts, sink, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchUnlocked", reflect.TypeOf((*MockIAccountsEvents)(nil).WatchUnlocked), opts, sink, identityHash, accountId)
}

// MockIAccountsFilterer is a mock of IAccountsFilterer interface
type MockIAccountsFilterer struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsFiltererMockRecorder
}

// MockIAccountsFiltererMockRecorder is the mock recorder for MockIAccountsFilterer
type MockIAccountsFiltererMockRecorder struct {
	mock *MockIAccountsFilterer
}

// NewMockIAccountsFilterer creates a new mock instance
func NewMockIAccountsFilterer(ctrl *gomock.Controller) *MockIAccountsFilterer {
	mock := &MockIAccountsFilterer{ctrl: ctrl}
	mock.recorder = &MockIAccountsFiltererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsFilterer) EXPECT() *MockIAccountsFiltererMockRecorder {
	return m.recorder
}

// FilterSignUp mocks base method
func (m *MockIAccountsFilterer) FilterSignUp(opts *bind.FilterOpts, owner []common.Address) (*adapter.AccountsSignUpIterator, error) {
	ret := m.ctrl.Call(m, "FilterSignUp", opts, owner)
	ret0, _ := ret[0].(*adapter.AccountsSignUpIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSignUp indicates an expected call of FilterSignUp
func (mr *MockIAccountsFiltererMockRecorder) FilterSignUp(opts, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSignUp", reflect.TypeOf((*MockIAccountsFilterer)(nil).FilterSignUp), opts, owner)
}

// FilterTemporaryCreated mocks base method
func (m *MockIAccountsFilterer) FilterTemporaryCreated(opts *bind.FilterOpts, proxy []common.Address, identityHash []common.Hash) (*adapter.AccountsTemporaryCreatedIterator, error) {
	ret := m.ctrl.Call(m, "FilterTemporaryCreated", opts, proxy, identityHash)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreatedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTemporaryCreated indicates an expected call of FilterTemporaryCreated
func (mr *MockIAccountsFiltererMockRecorder) FilterTemporaryCreated(opts, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTemporaryCreated", reflect.TypeOf((*MockIAccountsFilterer)(nil).FilterTemporaryCreated), opts, proxy, identityHash)
}

// FilterUnlocked mocks base method
func (m *MockIAccountsFilterer) FilterUnlocked(opts *bind.FilterOpts, identityHash []common.Hash, accountId []types.ID) (*adapter.AccountsUnlockedIterator, error) {
	ret := m.ctrl.Call(m, "FilterUnlocked", opts, identityHash, accountId)
	ret0, _ := ret[0].(*adapter.AccountsUnlockedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterUnlocked indicates an expected call of FilterUnlocked
func (mr *MockIAccountsFiltererMockRecorder) FilterUnlocked(opts, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUnlocked", reflect.TypeOf((*MockIAccountsFilterer)(nil).FilterUnlocked), opts, identityHash, accountId)
}

// MockIAccountsParser is a mock of IAccountsParser interface
type MockIAccountsParser struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsParserMockRecorder
}

// MockIAccountsParserMockRecorder is the mock recorder for MockIAccountsParser
type MockIAccountsParserMockRecorder struct {
	mock *MockIAccountsParser
}

// NewMockIAccountsParser creates a new mock instance
func NewMockIAccountsParser(ctrl *gomock.Controller) *MockIAccountsParser {
	mock := &MockIAccountsParser{ctrl: ctrl}
	mock.recorder = &MockIAccountsParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsParser) EXPECT() *MockIAccountsParserMockRecorder {
	return m.recorder
}

// ParseSignUpFromReceipt mocks base method
func (m *MockIAccountsParser) ParseSignUpFromReceipt(receipt *types0.Receipt) (*adapter.AccountsSignUp, error) {
	ret := m.ctrl.Call(m, "ParseSignUpFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsSignUp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSignUpFromReceipt indicates an expected call of ParseSignUpFromReceipt
func (mr *MockIAccountsParserMockRecorder) ParseSignUpFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSignUpFromReceipt", reflect.TypeOf((*MockIAccountsParser)(nil).ParseSignUpFromReceipt), receipt)
}

// ParseTemporaryCreatedFromReceipt mocks base method
func (m *MockIAccountsParser) ParseTemporaryCreatedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsTemporaryCreated, error) {
	ret := m.ctrl.Call(m, "ParseTemporaryCreatedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTemporaryCreatedFromReceipt indicates an expected call of ParseTemporaryCreatedFromReceipt
func (mr *MockIAccountsParserMockRecorder) ParseTemporaryCreatedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTemporaryCreatedFromReceipt", reflect.TypeOf((*MockIAccountsParser)(nil).ParseTemporaryCreatedFromReceipt), receipt)
}

// ParseUnlockedFromReceipt mocks base method
func (m *MockIAccountsParser) ParseUnlockedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsUnlocked, error) {
	ret := m.ctrl.Call(m, "ParseUnlockedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsUnlocked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseUnlockedFromReceipt indicates an expected call of ParseUnlockedFromReceipt
func (mr *MockIAccountsParserMockRecorder) ParseUnlockedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUnlockedFromReceipt", reflect.TypeOf((*MockIAccountsParser)(nil).ParseUnlockedFromReceipt), receipt)
}

// MockIAccountsWatcher is a mock of IAccountsWatcher interface
type MockIAccountsWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsWatcherMockRecorder
}

// MockIAccountsWatcherMockRecorder is the mock recorder for MockIAccountsWatcher
type MockIAccountsWatcherMockRecorder struct {
	mock *MockIAccountsWatcher
}

// NewMockIAccountsWatcher creates a new mock instance
func NewMockIAccountsWatcher(ctrl *gomock.Controller) *MockIAccountsWatcher {
	mock := &MockIAccountsWatcher{ctrl: ctrl}
	mock.recorder = &MockIAccountsWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsWatcher) EXPECT() *MockIAccountsWatcherMockRecorder {
	return m.recorder
}

// WatchSignUp mocks base method
func (m *MockIAccountsWatcher) WatchSignUp(opts *bind.WatchOpts, sink chan<- *adapter.AccountsSignUp, owner []common.Address) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchSignUp", opts, sink, owner)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchSignUp indicates an expected call of WatchSignUp
func (mr *MockIAccountsWatcherMockRecorder) WatchSignUp(opts, sink, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchSignUp", reflect.TypeOf((*MockIAccountsWatcher)(nil).WatchSignUp), opts, sink, owner)
}

// WatchTemporaryCreated mocks base method
func (m *MockIAccountsWatcher) WatchTemporaryCreated(opts *bind.WatchOpts, sink chan<- *adapter.AccountsTemporaryCreated, proxy []common.Address, identityHash []common.Hash) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchTemporaryCreated", opts, sink, proxy, identityHash)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchTemporaryCreated indicates an expected call of WatchTemporaryCreated
func (mr *MockIAccountsWatcherMockRecorder) WatchTemporaryCreated(opts, sink, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchTemporaryCreated", reflect.TypeOf((*MockIAccountsWatcher)(nil).WatchTemporaryCreated), opts, sink, proxy, identityHash)
}

// WatchUnlocked mocks base method
func (m *MockIAccountsWatcher) WatchUnlocked(opts *bind.WatchOpts, sink chan<- *adapter.AccountsUnlocked, identityHash []common.Hash, accountId []types.ID) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchUnlocked", opts, sink, identityHash, accountId)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchUnlocked indicates an expected call of WatchUnlocked
func (mr *MockIAccountsWatcherMockRecorder) WatchUnlocked(opts, sink, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchUnlocked", reflect.TypeOf((*MockIAccountsWatcher)(nil).WatchUnlocked), opts, sink, identityHash, accountId)
}

// MockIAccountsContract is a mock of IAccountsContract interface
type MockIAccountsContract struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsContractMockRecorder
}

// MockIAccountsContractMockRecorder is the mock recorder for MockIAccountsContract
type MockIAccountsContractMockRecorder struct {
	mock *MockIAccountsContract
}

// NewMockIAccountsContract creates a new mock instance
func NewMockIAccountsContract(ctrl *gomock.Controller) *MockIAccountsContract {
	mock := &MockIAccountsContract{ctrl: ctrl}
	mock.recorder = &MockIAccountsContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsContract) EXPECT() *MockIAccountsContractMockRecorder {
	return m.recorder
}

// Address mocks base method
func (m *MockIAccountsContract) Address() common.Address {
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(common.Address)
	return ret0
}

// Address indicates an expected call of Address
func (mr *MockIAccountsContractMockRecorder) Address() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockIAccountsContract)(nil).Address))
}

// TxHash mocks base method
func (m *MockIAccountsContract) TxHash() common.Hash {
	ret := m.ctrl.Call(m, "TxHash")
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// TxHash indicates an expected call of TxHash
func (mr *MockIAccountsContractMockRecorder) TxHash() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxHash", reflect.TypeOf((*MockIAccountsContract)(nil).TxHash))
}

// CreatedAt mocks base method
func (m *MockIAccountsContract) CreatedAt() *big.Int {
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt
func (mr *MockIAccountsContractMockRecorder) CreatedAt() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockIAccountsContract)(nil).CreatedAt))
}

// Accounts mocks base method
func (m *MockIAccountsContract) Accounts(arg0 types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "Accounts", arg0)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accounts indicates an expected call of Accounts
func (mr *MockIAccountsContractMockRecorder) Accounts(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockIAccountsContract)(nil).Accounts), arg0)
}

// Exists mocks base method
func (m *MockIAccountsContract) Exists(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "Exists", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists
func (mr *MockIAccountsContractMockRecorder) Exists(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIAccountsContract)(nil).Exists), accountId)
}

// GetAccount mocks base method
func (m *MockIAccountsContract) GetAccount(accountId types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "GetAccount", accountId)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount
func (mr *MockIAccountsContractMockRecorder) GetAccount(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIAccountsContract)(nil).GetAccount), accountId)
}

// GetAccountId mocks base method
func (m *MockIAccountsContract) GetAccountId(sender common.Address) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountId", sender)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId
func (mr *MockIAccountsContractMockRecorder) GetAccountId(sender interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockIAccountsContract)(nil).GetAccountId), sender)
}

// GetAccountIdFromSignature mocks base method
func (m *MockIAccountsContract) GetAccountIdFromSignature(messageHash common.Hash, signature []byte) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountIdFromSignature", messageHash, signature)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdFromSignature indicates an expected call of GetAccountIdFromSignature
func (mr *MockIAccountsContractMockRecorder) GetAccountIdFromSignature(messageHash, signature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdFromSignature", reflect.TypeOf((*MockIAccountsContract)(nil).GetAccountIdFromSignature), messageHash, signature)
}

// IdentityHashToAccount mocks base method
func (m *MockIAccountsContract) IdentityHashToAccount(arg0 common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "IdentityHashToAccount", arg0)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityHashToAccount indicates an expected call of IdentityHashToAccount
func (mr *MockIAccountsContractMockRecorder) IdentityHashToAccount(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityHashToAccount", reflect.TypeOf((*MockIAccountsContract)(nil).IdentityHashToAccount), arg0)
}

// IsControllerOf mocks base method
func (m *MockIAccountsContract) IsControllerOf(sender common.Address, accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsControllerOf", sender, accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsControllerOf indicates an expected call of IsControllerOf
func (mr *MockIAccountsContractMockRecorder) IsControllerOf(sender, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsControllerOf", reflect.TypeOf((*MockIAccountsContract)(nil).IsControllerOf), sender, accountId)
}

// IsTemporary mocks base method
func (m *MockIAccountsContract) IsTemporary(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsTemporary", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemporary indicates an expected call of IsTemporary
func (mr *MockIAccountsContractMockRecorder) IsTemporary(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemporary", reflect.TypeOf((*MockIAccountsContract)(nil).IsTemporary), accountId)
}

// NumberOfAccounts mocks base method
func (m *MockIAccountsContract) NumberOfAccounts() (*big.Int, error) {
	ret := m.ctrl.Call(m, "NumberOfAccounts")
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberOfAccounts indicates an expected call of NumberOfAccounts
func (mr *MockIAccountsContractMockRecorder) NumberOfAccounts() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfAccounts", reflect.TypeOf((*MockIAccountsContract)(nil).NumberOfAccounts))
}

// Create mocks base method
func (m *MockIAccountsContract) Create(ctx context.Context) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIAccountsContractMockRecorder) Create(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountsContract)(nil).Create), ctx)
}

// CreateTemporary mocks base method
func (m *MockIAccountsContract) CreateTemporary(ctx context.Context, identityHash common.Hash) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "CreateTemporary", ctx, identityHash)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemporary indicates an expected call of CreateTemporary
func (mr *MockIAccountsContractMockRecorder) CreateTemporary(ctx, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemporary", reflect.TypeOf((*MockIAccountsContract)(nil).CreateTemporary), ctx, identityHash)
}

// SetController mocks base method
func (m *MockIAccountsContract) SetController(ctx context.Context, controller common.Address) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "SetController", ctx, controller)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetController indicates an expected call of SetController
func (mr *MockIAccountsContractMockRecorder) SetController(ctx, controller interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetController", reflect.TypeOf((*MockIAccountsContract)(nil).SetController), ctx, controller)
}

// UnlockTemporary mocks base method
func (m *MockIAccountsContract) UnlockTemporary(ctx context.Context, identityPreimage common.Hash, newOwner common.Address, passwordSignature []byte) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "UnlockTemporary", ctx, identityPreimage, newOwner, passwordSignature)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockTemporary indicates an expected call of UnlockTemporary
func (mr *MockIAccountsContractMockRecorder) UnlockTemporary(ctx, identityPreimage, newOwner, passwordSignature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTemporary", reflect.TypeOf((*MockIAccountsContract)(nil).UnlockTemporary), ctx, identityPreimage, newOwner, passwordSignature)
}

// FilterSignUp mocks base method
func (m *MockIAccountsContract) FilterSignUp(opts *bind.FilterOpts, owner []common.Address) (*adapter.AccountsSignUpIterator, error) {
	ret := m.ctrl.Call(m, "FilterSignUp", opts, owner)
	ret0, _ := ret[0].(*adapter.AccountsSignUpIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSignUp indicates an expected call of FilterSignUp
func (mr *MockIAccountsContractMockRecorder) FilterSignUp(opts, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSignUp", reflect.TypeOf((*MockIAccountsContract)(nil).FilterSignUp), opts, owner)
}

// FilterTemporaryCreated mocks base method
func (m *MockIAccountsContract) FilterTemporaryCreated(opts *bind.FilterOpts, proxy []common.Address, identityHash []common.Hash) (*adapter.AccountsTemporaryCreatedIterator, error) {
	ret := m.ctrl.Call(m, "FilterTemporaryCreated", opts, proxy, identityHash)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreatedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTemporaryCreated indicates an expected call of FilterTemporaryCreated
func (mr *MockIAccountsContractMockRecorder) FilterTemporaryCreated(opts, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTemporaryCreated", reflect.TypeOf((*MockIAccountsContract)(nil).FilterTemporaryCreated), opts, proxy, identityHash)
}

// FilterUnlocked mocks base method
func (m *MockIAccountsContract) FilterUnlocked(opts *bind.FilterOpts, identityHash []common.Hash, accountId []types.ID) (*adapter.AccountsUnlockedIterator, error) {
	ret := m.ctrl.Call(m, "FilterUnlocked", opts, identityHash, accountId)
	ret0, _ := ret[0].(*adapter.AccountsUnlockedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterUnlocked indicates an expected call of FilterUnlocked
func (mr *MockIAccountsContractMockRecorder) FilterUnlocked(opts, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUnlocked", reflect.TypeOf((*MockIAccountsContract)(nil).FilterUnlocked), opts, identityHash, accountId)
}

// ParseSignUpFromReceipt mocks base method
func (m *MockIAccountsContract) ParseSignUpFromReceipt(receipt *types0.Receipt) (*adapter.AccountsSignUp, error) {
	ret := m.ctrl.Call(m, "ParseSignUpFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsSignUp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSignUpFromReceipt indicates an expected call of ParseSignUpFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseSignUpFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSignUpFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseSignUpFromReceipt), receipt)
}

// ParseTemporaryCreatedFromReceipt mocks base method
func (m *MockIAccountsContract) ParseTemporaryCreatedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsTemporaryCreated, error) {
	ret := m.ctrl.Call(m, "ParseTemporaryCreatedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTemporaryCreatedFromReceipt indicates an expected call of ParseTemporaryCreatedFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseTemporaryCreatedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTemporaryCreatedFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseTemporaryCreatedFromReceipt), receipt)
}

// ParseUnlockedFromReceipt mocks base method
func (m *MockIAccountsContract) ParseUnlockedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsUnlocked, error) {
	ret := m.ctrl.Call(m, "ParseUnlockedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsUnlocked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseUnlockedFromReceipt indicates an expected call of ParseUnlockedFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseUnlockedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUnlockedFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseUnlockedFromReceipt), receipt)
}

// WatchSignUp mocks base method
func (m *MockIAccountsContract) WatchSignUp(opts *bind.WatchOpts, sink chan<- *adapter.AccountsSignUp, owner []common.Address) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchSignUp", opts, sink, owner)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchSignUp indicates an expected call of WatchSignUp
func (mr *MockIAccountsContractMockRecorder) WatchSignUp(opts, sink, owner interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchSignUp", reflect.TypeOf((*MockIAccountsContract)(nil).WatchSignUp), opts, sink, owner)
}

// WatchTemporaryCreated mocks base method
func (m *MockIAccountsContract) WatchTemporaryCreated(opts *bind.WatchOpts, sink chan<- *adapter.AccountsTemporaryCreated, proxy []common.Address, identityHash []common.Hash) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchTemporaryCreated", opts, sink, proxy, identityHash)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchTemporaryCreated indicates an expected call of WatchTemporaryCreated
func (mr *MockIAccountsContractMockRecorder) WatchTemporaryCreated(opts, sink, proxy, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchTemporaryCreated", reflect.TypeOf((*MockIAccountsContract)(nil).WatchTemporaryCreated), opts, sink, proxy, identityHash)
}

// WatchUnlocked mocks base method
func (m *MockIAccountsContract) WatchUnlocked(opts *bind.WatchOpts, sink chan<- *adapter.AccountsUnlocked, identityHash []common.Hash, accountId []types.ID) (event.Subscription, error) {
	ret := m.ctrl.Call(m, "WatchUnlocked", opts, sink, identityHash, accountId)
	ret0, _ := ret[0].(event.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchUnlocked indicates an expected call of WatchUnlocked
func (mr *MockIAccountsContractMockRecorder) WatchUnlocked(opts, sink, identityHash, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchUnlocked", reflect.TypeOf((*MockIAccountsContract)(nil).WatchUnlocked), opts, sink, identityHash, accountId)
}
