// Code generated by MockGen. DO NOT EDIT.
// Source: accounts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	adapter "github.com/airbloc/airbloc-go/shared/adapter"
	types "github.com/airbloc/airbloc-go/shared/types"
	common "github.com/ethereum/go-ethereum/common"
	types0 "github.com/ethereum/go-ethereum/core/types"
	gomock "github.com/golang/mock/gomock"
)

// MockIAccountsManager is a mock of IAccountsManager interface
type MockIAccountsManager struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsManagerMockRecorder
}

// MockIAccountsManagerMockRecorder is the mock recorder for MockIAccountsManager
type MockIAccountsManagerMockRecorder struct {
	mock *MockIAccountsManager
}

// NewMockIAccountsManager creates a new mock instance
func NewMockIAccountsManager(ctrl *gomock.Controller) *MockIAccountsManager {
	mock := &MockIAccountsManager{ctrl: ctrl}
	mock.recorder = &MockIAccountsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsManager) EXPECT() *MockIAccountsManagerMockRecorder {
	return m.recorder
}

// Accounts mocks base method
func (m *MockIAccountsManager) Accounts(arg0 types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "Accounts", arg0)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accounts indicates an expected call of Accounts
func (mr *MockIAccountsManagerMockRecorder) Accounts(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockIAccountsManager)(nil).Accounts), arg0)
}

// Exists mocks base method
func (m *MockIAccountsManager) Exists(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "Exists", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists
func (mr *MockIAccountsManagerMockRecorder) Exists(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIAccountsManager)(nil).Exists), accountId)
}

// GetAccount mocks base method
func (m *MockIAccountsManager) GetAccount(accountId types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "GetAccount", accountId)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount
func (mr *MockIAccountsManagerMockRecorder) GetAccount(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIAccountsManager)(nil).GetAccount), accountId)
}

// GetAccountId mocks base method
func (m *MockIAccountsManager) GetAccountId(sender common.Address) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountId", sender)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId
func (mr *MockIAccountsManagerMockRecorder) GetAccountId(sender interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockIAccountsManager)(nil).GetAccountId), sender)
}

// GetAccountIdFromSignature mocks base method
func (m *MockIAccountsManager) GetAccountIdFromSignature(messageHash common.Hash, signature []byte) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountIdFromSignature", messageHash, signature)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdFromSignature indicates an expected call of GetAccountIdFromSignature
func (mr *MockIAccountsManagerMockRecorder) GetAccountIdFromSignature(messageHash, signature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdFromSignature", reflect.TypeOf((*MockIAccountsManager)(nil).GetAccountIdFromSignature), messageHash, signature)
}

// IdentityHashToAccount mocks base method
func (m *MockIAccountsManager) IdentityHashToAccount(arg0 common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "IdentityHashToAccount", arg0)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityHashToAccount indicates an expected call of IdentityHashToAccount
func (mr *MockIAccountsManagerMockRecorder) IdentityHashToAccount(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityHashToAccount", reflect.TypeOf((*MockIAccountsManager)(nil).IdentityHashToAccount), arg0)
}

// IsControllerOf mocks base method
func (m *MockIAccountsManager) IsControllerOf(sender common.Address, accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsControllerOf", sender, accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsControllerOf indicates an expected call of IsControllerOf
func (mr *MockIAccountsManagerMockRecorder) IsControllerOf(sender, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsControllerOf", reflect.TypeOf((*MockIAccountsManager)(nil).IsControllerOf), sender, accountId)
}

// IsTemporary mocks base method
func (m *MockIAccountsManager) IsTemporary(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsTemporary", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemporary indicates an expected call of IsTemporary
func (mr *MockIAccountsManagerMockRecorder) IsTemporary(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemporary", reflect.TypeOf((*MockIAccountsManager)(nil).IsTemporary), accountId)
}

// NumberOfAccounts mocks base method
func (m *MockIAccountsManager) NumberOfAccounts() (*big.Int, error) {
	ret := m.ctrl.Call(m, "NumberOfAccounts")
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberOfAccounts indicates an expected call of NumberOfAccounts
func (mr *MockIAccountsManagerMockRecorder) NumberOfAccounts() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfAccounts", reflect.TypeOf((*MockIAccountsManager)(nil).NumberOfAccounts))
}

// Create mocks base method
func (m *MockIAccountsManager) Create(ctx context.Context) (types.ID, error) {
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIAccountsManagerMockRecorder) Create(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountsManager)(nil).Create), ctx)
}

// CreateTemporary mocks base method
func (m *MockIAccountsManager) CreateTemporary(ctx context.Context, identityHash common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "CreateTemporary", ctx, identityHash)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemporary indicates an expected call of CreateTemporary
func (mr *MockIAccountsManagerMockRecorder) CreateTemporary(ctx, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemporary", reflect.TypeOf((*MockIAccountsManager)(nil).CreateTemporary), ctx, identityHash)
}

// SetController mocks base method
func (m *MockIAccountsManager) SetController(ctx context.Context, controller common.Address) error {
	ret := m.ctrl.Call(m, "SetController", ctx, controller)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetController indicates an expected call of SetController
func (mr *MockIAccountsManagerMockRecorder) SetController(ctx, controller interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetController", reflect.TypeOf((*MockIAccountsManager)(nil).SetController), ctx, controller)
}

// UnlockTemporary mocks base method
func (m *MockIAccountsManager) UnlockTemporary(ctx context.Context, identityPreimage common.Hash, newOwner common.Address, passwordSignature []byte) error {
	ret := m.ctrl.Call(m, "UnlockTemporary", ctx, identityPreimage, newOwner, passwordSignature)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockTemporary indicates an expected call of UnlockTemporary
func (mr *MockIAccountsManagerMockRecorder) UnlockTemporary(ctx, identityPreimage, newOwner, passwordSignature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTemporary", reflect.TypeOf((*MockIAccountsManager)(nil).UnlockTemporary), ctx, identityPreimage, newOwner, passwordSignature)
}

// MockIAccountsContract is a mock of IAccountsContract interface
type MockIAccountsContract struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountsContractMockRecorder
}

// MockIAccountsContractMockRecorder is the mock recorder for MockIAccountsContract
type MockIAccountsContractMockRecorder struct {
	mock *MockIAccountsContract
}

// NewMockIAccountsContract creates a new mock instance
func NewMockIAccountsContract(ctrl *gomock.Controller) *MockIAccountsContract {
	mock := &MockIAccountsContract{ctrl: ctrl}
	mock.recorder = &MockIAccountsContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAccountsContract) EXPECT() *MockIAccountsContractMockRecorder {
	return m.recorder
}

// Accounts mocks base method
func (m *MockIAccountsContract) Accounts(arg0 types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "Accounts", arg0)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accounts indicates an expected call of Accounts
func (mr *MockIAccountsContractMockRecorder) Accounts(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockIAccountsContract)(nil).Accounts), arg0)
}

// Exists mocks base method
func (m *MockIAccountsContract) Exists(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "Exists", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists
func (mr *MockIAccountsContractMockRecorder) Exists(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIAccountsContract)(nil).Exists), accountId)
}

// GetAccount mocks base method
func (m *MockIAccountsContract) GetAccount(accountId types.ID) (types.Account, error) {
	ret := m.ctrl.Call(m, "GetAccount", accountId)
	ret0, _ := ret[0].(types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount
func (mr *MockIAccountsContractMockRecorder) GetAccount(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIAccountsContract)(nil).GetAccount), accountId)
}

// GetAccountId mocks base method
func (m *MockIAccountsContract) GetAccountId(sender common.Address) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountId", sender)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId
func (mr *MockIAccountsContractMockRecorder) GetAccountId(sender interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockIAccountsContract)(nil).GetAccountId), sender)
}

// GetAccountIdFromSignature mocks base method
func (m *MockIAccountsContract) GetAccountIdFromSignature(messageHash common.Hash, signature []byte) (types.ID, error) {
	ret := m.ctrl.Call(m, "GetAccountIdFromSignature", messageHash, signature)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdFromSignature indicates an expected call of GetAccountIdFromSignature
func (mr *MockIAccountsContractMockRecorder) GetAccountIdFromSignature(messageHash, signature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdFromSignature", reflect.TypeOf((*MockIAccountsContract)(nil).GetAccountIdFromSignature), messageHash, signature)
}

// IdentityHashToAccount mocks base method
func (m *MockIAccountsContract) IdentityHashToAccount(arg0 common.Hash) (types.ID, error) {
	ret := m.ctrl.Call(m, "IdentityHashToAccount", arg0)
	ret0, _ := ret[0].(types.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityHashToAccount indicates an expected call of IdentityHashToAccount
func (mr *MockIAccountsContractMockRecorder) IdentityHashToAccount(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityHashToAccount", reflect.TypeOf((*MockIAccountsContract)(nil).IdentityHashToAccount), arg0)
}

// IsControllerOf mocks base method
func (m *MockIAccountsContract) IsControllerOf(sender common.Address, accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsControllerOf", sender, accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsControllerOf indicates an expected call of IsControllerOf
func (mr *MockIAccountsContractMockRecorder) IsControllerOf(sender, accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsControllerOf", reflect.TypeOf((*MockIAccountsContract)(nil).IsControllerOf), sender, accountId)
}

// IsTemporary mocks base method
func (m *MockIAccountsContract) IsTemporary(accountId types.ID) (bool, error) {
	ret := m.ctrl.Call(m, "IsTemporary", accountId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemporary indicates an expected call of IsTemporary
func (mr *MockIAccountsContractMockRecorder) IsTemporary(accountId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemporary", reflect.TypeOf((*MockIAccountsContract)(nil).IsTemporary), accountId)
}

// NumberOfAccounts mocks base method
func (m *MockIAccountsContract) NumberOfAccounts() (*big.Int, error) {
	ret := m.ctrl.Call(m, "NumberOfAccounts")
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumberOfAccounts indicates an expected call of NumberOfAccounts
func (mr *MockIAccountsContractMockRecorder) NumberOfAccounts() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumberOfAccounts", reflect.TypeOf((*MockIAccountsContract)(nil).NumberOfAccounts))
}

// Create mocks base method
func (m *MockIAccountsContract) Create(ctx context.Context) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIAccountsContractMockRecorder) Create(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountsContract)(nil).Create), ctx)
}

// CreateTemporary mocks base method
func (m *MockIAccountsContract) CreateTemporary(ctx context.Context, identityHash common.Hash) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "CreateTemporary", ctx, identityHash)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemporary indicates an expected call of CreateTemporary
func (mr *MockIAccountsContractMockRecorder) CreateTemporary(ctx, identityHash interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemporary", reflect.TypeOf((*MockIAccountsContract)(nil).CreateTemporary), ctx, identityHash)
}

// SetController mocks base method
func (m *MockIAccountsContract) SetController(ctx context.Context, controller common.Address) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "SetController", ctx, controller)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetController indicates an expected call of SetController
func (mr *MockIAccountsContractMockRecorder) SetController(ctx, controller interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetController", reflect.TypeOf((*MockIAccountsContract)(nil).SetController), ctx, controller)
}

// UnlockTemporary mocks base method
func (m *MockIAccountsContract) UnlockTemporary(ctx context.Context, identityPreimage common.Hash, newOwner common.Address, passwordSignature []byte) (*types0.Receipt, error) {
	ret := m.ctrl.Call(m, "UnlockTemporary", ctx, identityPreimage, newOwner, passwordSignature)
	ret0, _ := ret[0].(*types0.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockTemporary indicates an expected call of UnlockTemporary
func (mr *MockIAccountsContractMockRecorder) UnlockTemporary(ctx, identityPreimage, newOwner, passwordSignature interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTemporary", reflect.TypeOf((*MockIAccountsContract)(nil).UnlockTemporary), ctx, identityPreimage, newOwner, passwordSignature)
}

// ParseControllerChangedFromReceipt mocks base method
func (m *MockIAccountsContract) ParseControllerChangedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsControllerChanged, error) {
	ret := m.ctrl.Call(m, "ParseControllerChangedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsControllerChanged)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseControllerChangedFromReceipt indicates an expected call of ParseControllerChangedFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseControllerChangedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseControllerChangedFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseControllerChangedFromReceipt), receipt)
}

// ParseSignUpFromReceipt mocks base method
func (m *MockIAccountsContract) ParseSignUpFromReceipt(receipt *types0.Receipt) (*adapter.AccountsSignUp, error) {
	ret := m.ctrl.Call(m, "ParseSignUpFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsSignUp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSignUpFromReceipt indicates an expected call of ParseSignUpFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseSignUpFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSignUpFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseSignUpFromReceipt), receipt)
}

// ParseTemporaryCreatedFromReceipt mocks base method
func (m *MockIAccountsContract) ParseTemporaryCreatedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsTemporaryCreated, error) {
	ret := m.ctrl.Call(m, "ParseTemporaryCreatedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsTemporaryCreated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTemporaryCreatedFromReceipt indicates an expected call of ParseTemporaryCreatedFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseTemporaryCreatedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTemporaryCreatedFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseTemporaryCreatedFromReceipt), receipt)
}

// ParseUnlockedFromReceipt mocks base method
func (m *MockIAccountsContract) ParseUnlockedFromReceipt(receipt *types0.Receipt) (*adapter.AccountsUnlocked, error) {
	ret := m.ctrl.Call(m, "ParseUnlockedFromReceipt", receipt)
	ret0, _ := ret[0].(*adapter.AccountsUnlocked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseUnlockedFromReceipt indicates an expected call of ParseUnlockedFromReceipt
func (mr *MockIAccountsContractMockRecorder) ParseUnlockedFromReceipt(receipt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUnlockedFromReceipt", reflect.TypeOf((*MockIAccountsContract)(nil).ParseUnlockedFromReceipt), receipt)
}
