// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/p2p/v1/dauth.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DAuthSignUpRequest struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	IdentityHash         string   `protobuf:"bytes,2,opt,name=identityHash,proto3" json:"identityHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DAuthSignUpRequest) Reset()         { *m = DAuthSignUpRequest{} }
func (m *DAuthSignUpRequest) String() string { return proto.CompactTextString(m) }
func (*DAuthSignUpRequest) ProtoMessage()    {}
func (*DAuthSignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b4b5d564e7416f, []int{0}
}

func (m *DAuthSignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DAuthSignUpRequest.Unmarshal(m, b)
}
func (m *DAuthSignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DAuthSignUpRequest.Marshal(b, m, deterministic)
}
func (m *DAuthSignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DAuthSignUpRequest.Merge(m, src)
}
func (m *DAuthSignUpRequest) XXX_Size() int {
	return xxx_messageInfo_DAuthSignUpRequest.Size(m)
}
func (m *DAuthSignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DAuthSignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DAuthSignUpRequest proto.InternalMessageInfo

func (m *DAuthSignUpRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *DAuthSignUpRequest) GetIdentityHash() string {
	if m != nil {
		return m.IdentityHash
	}
	return ""
}

type DAuthSignUpResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DAuthSignUpResponse) Reset()         { *m = DAuthSignUpResponse{} }
func (m *DAuthSignUpResponse) String() string { return proto.CompactTextString(m) }
func (*DAuthSignUpResponse) ProtoMessage()    {}
func (*DAuthSignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b4b5d564e7416f, []int{1}
}

func (m *DAuthSignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DAuthSignUpResponse.Unmarshal(m, b)
}
func (m *DAuthSignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DAuthSignUpResponse.Marshal(b, m, deterministic)
}
func (m *DAuthSignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DAuthSignUpResponse.Merge(m, src)
}
func (m *DAuthSignUpResponse) XXX_Size() int {
	return xxx_messageInfo_DAuthSignUpResponse.Size(m)
}
func (m *DAuthSignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DAuthSignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DAuthSignUpResponse proto.InternalMessageInfo

func (m *DAuthSignUpResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//*
// DAuth (Data Collection Authentification) API.
type DAuthRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CollectionId         string   `protobuf:"bytes,2,opt,name=collectionId,proto3" json:"collectionId,omitempty"`
	Allow                bool     `protobuf:"varint,3,opt,name=allow,proto3" json:"allow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DAuthRequest) Reset()         { *m = DAuthRequest{} }
func (m *DAuthRequest) String() string { return proto.CompactTextString(m) }
func (*DAuthRequest) ProtoMessage()    {}
func (*DAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b4b5d564e7416f, []int{2}
}

func (m *DAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DAuthRequest.Unmarshal(m, b)
}
func (m *DAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DAuthRequest.Marshal(b, m, deterministic)
}
func (m *DAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DAuthRequest.Merge(m, src)
}
func (m *DAuthRequest) XXX_Size() int {
	return xxx_messageInfo_DAuthRequest.Size(m)
}
func (m *DAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DAuthRequest proto.InternalMessageInfo

func (m *DAuthRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DAuthRequest) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

func (m *DAuthRequest) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

type DAuthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DAuthResponse) Reset()         { *m = DAuthResponse{} }
func (m *DAuthResponse) String() string { return proto.CompactTextString(m) }
func (*DAuthResponse) ProtoMessage()    {}
func (*DAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b4b5d564e7416f, []int{3}
}

func (m *DAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DAuthResponse.Unmarshal(m, b)
}
func (m *DAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DAuthResponse.Marshal(b, m, deterministic)
}
func (m *DAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DAuthResponse.Merge(m, src)
}
func (m *DAuthResponse) XXX_Size() int {
	return xxx_messageInfo_DAuthResponse.Size(m)
}
func (m *DAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DAuthResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DAuthSignUpRequest)(nil), "airbloc.p2p.v1.DAuthSignUpRequest")
	proto.RegisterType((*DAuthSignUpResponse)(nil), "airbloc.p2p.v1.DAuthSignUpResponse")
	proto.RegisterType((*DAuthRequest)(nil), "airbloc.p2p.v1.DAuthRequest")
	proto.RegisterType((*DAuthResponse)(nil), "airbloc.p2p.v1.DAuthResponse")
}

func init() { proto.RegisterFile("proto/p2p/v1/dauth.proto", fileDescriptor_d6b4b5d564e7416f) }

var fileDescriptor_d6b4b5d564e7416f = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0x10, 0xa8, 0x3d, 0x15, 0x90, 0x0c, 0x43, 0x84, 0x18, 0x2a, 0x4f, 0x15, 0x82,
	0x58, 0x6d, 0x9f, 0x00, 0xc4, 0x40, 0xd7, 0x00, 0x0b, 0x9b, 0x63, 0x9b, 0xc4, 0x92, 0xf1, 0x99,
	0xe4, 0x1c, 0xc4, 0xdb, 0x23, 0xdc, 0x04, 0xda, 0x85, 0xc9, 0xfa, 0x3f, 0xdb, 0x77, 0x9f, 0x7e,
	0xc8, 0x43, 0x8b, 0x84, 0x22, 0xac, 0x82, 0xe8, 0x97, 0x42, 0xcb, 0x48, 0x4d, 0x91, 0x10, 0x3b,
	0x95, 0xb6, 0xad, 0x1c, 0xaa, 0x22, 0xac, 0x42, 0xd1, 0x2f, 0xf9, 0x33, 0xb0, 0x87, 0xbb, 0x48,
	0xcd, 0x93, 0xad, 0xfd, 0x4b, 0x28, 0xcd, 0x47, 0x34, 0x1d, 0xb1, 0x4b, 0x98, 0x84, 0x16, 0x7b,
	0xab, 0x4d, 0x9b, 0x67, 0xf3, 0x6c, 0x31, 0x2d, 0x7f, 0x33, 0xe3, 0x30, 0xb3, 0xda, 0x78, 0xb2,
	0xf4, 0xf5, 0x28, 0xbb, 0x26, 0x3f, 0x48, 0xf7, 0x7b, 0x8c, 0xaf, 0xe1, 0x7c, 0x6f, 0x6a, 0x17,
	0xd0, 0x77, 0x86, 0x5d, 0xc1, 0x54, 0x2a, 0x85, 0xd1, 0xd3, 0x46, 0x0f, 0x73, 0xff, 0x00, 0x7f,
	0x83, 0x59, 0xfa, 0x34, 0x4a, 0xfc, 0xfb, 0xfa, 0x47, 0x43, 0xa1, 0x73, 0x46, 0x91, 0x45, 0xbf,
	0xd1, 0xa3, 0xc6, 0x2e, 0x63, 0x17, 0x70, 0x24, 0x9d, 0xc3, 0xcf, 0xfc, 0x70, 0x9e, 0x2d, 0x26,
	0xe5, 0x36, 0xf0, 0x33, 0x38, 0x19, 0xf6, 0x6c, 0xb5, 0xee, 0x6f, 0x5e, 0xaf, 0x6b, 0x4b, 0x4d,
	0xac, 0x0a, 0x85, 0xef, 0x62, 0x28, 0x68, 0x3c, 0x6f, 0x6b, 0x14, 0xbb, 0x6d, 0x56, 0xc7, 0x29,
	0xad, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x07, 0xdb, 0xd4, 0xde, 0x64, 0x01, 0x00, 0x00,
}
