// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/p2p/v1/rpc.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPCResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SuccessfulReply      []byte   `protobuf:"bytes,3,opt,name=successfulReply,proto3" json:"successfulReply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCResponse) Reset()         { *m = RPCResponse{} }
func (m *RPCResponse) String() string { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()    {}
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e48d89397e3cf4c, []int{0}
}

func (m *RPCResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCResponse.Unmarshal(m, b)
}
func (m *RPCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCResponse.Marshal(b, m, deterministic)
}
func (m *RPCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCResponse.Merge(m, src)
}
func (m *RPCResponse) XXX_Size() int {
	return xxx_messageInfo_RPCResponse.Size(m)
}
func (m *RPCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RPCResponse proto.InternalMessageInfo

func (m *RPCResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RPCResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RPCResponse) GetSuccessfulReply() []byte {
	if m != nil {
		return m.SuccessfulReply
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCResponse)(nil), "airbloc.p2p.v1.RPCResponse")
}

func init() { proto.RegisterFile("proto/p2p/v1/rpc.proto", fileDescriptor_4e48d89397e3cf4c) }

var fileDescriptor_4e48d89397e3cf4c = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x30, 0x2a, 0xd0, 0x2f, 0x33, 0xd4, 0x2f, 0x2a, 0x48, 0xd6, 0x03, 0x0b, 0x08,
	0xf1, 0x25, 0x66, 0x16, 0x25, 0xe5, 0xe4, 0x27, 0xeb, 0x15, 0x18, 0x15, 0xe8, 0x95, 0x19, 0x2a,
	0xc5, 0x72, 0x71, 0x07, 0x05, 0x38, 0x07, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xf1,
	0x71, 0x31, 0xe5, 0x67, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0x31, 0xe5, 0x67, 0x0b, 0x89,
	0x70, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38,
	0x42, 0x1a, 0x5c, 0xfc, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x69, 0xa5, 0x39, 0x41, 0xa9,
	0x05, 0x39, 0x95, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0xe8, 0xc2, 0x4e, 0x3a, 0x51, 0x5a,
	0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x50, 0xbb, 0x61, 0xb4, 0x6e,
	0x7a, 0xbe, 0x3e, 0xb2, 0x33, 0x93, 0xd8, 0xc0, 0x3c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x51, 0x55, 0xce, 0xf8, 0xbd, 0x00, 0x00, 0x00,
}
